/*
 * This file is generated by jOOQ.
 */
package com.example.boot.data.database.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CheckItemInfo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private Long          catalogId;
    private String        code;
    private String        createdBy;
    private LocalDateTime createdDate;
    private Integer       isDeleted;
    private String        mode;
    private String        modifiedBy;
    private LocalDateTime modifiedDate;
    private String        name;
    private String        position;

    public CheckItemInfo() {}

    public CheckItemInfo(CheckItemInfo value) {
        this.id = value.id;
        this.catalogId = value.catalogId;
        this.code = value.code;
        this.createdBy = value.createdBy;
        this.createdDate = value.createdDate;
        this.isDeleted = value.isDeleted;
        this.mode = value.mode;
        this.modifiedBy = value.modifiedBy;
        this.modifiedDate = value.modifiedDate;
        this.name = value.name;
        this.position = value.position;
    }

    public CheckItemInfo(
        Long          id,
        Long          catalogId,
        String        code,
        String        createdBy,
        LocalDateTime createdDate,
        Integer       isDeleted,
        String        mode,
        String        modifiedBy,
        LocalDateTime modifiedDate,
        String        name,
        String        position
    ) {
        this.id = id;
        this.catalogId = catalogId;
        this.code = code;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.isDeleted = isDeleted;
        this.mode = mode;
        this.modifiedBy = modifiedBy;
        this.modifiedDate = modifiedDate;
        this.name = name;
        this.position = position;
    }

    /**
     * Getter for <code>physical_examination_system.check_item_info.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>physical_examination_system.check_item_info.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>physical_examination_system.check_item_info.catalog_id</code>.
     */
    public Long getCatalogId() {
        return this.catalogId;
    }

    /**
     * Setter for <code>physical_examination_system.check_item_info.catalog_id</code>.
     */
    public void setCatalogId(Long catalogId) {
        this.catalogId = catalogId;
    }

    /**
     * Getter for <code>physical_examination_system.check_item_info.code</code>.
     */
    public String getCode() {
        return this.code;
    }

    /**
     * Setter for <code>physical_examination_system.check_item_info.code</code>.
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * Getter for <code>physical_examination_system.check_item_info.created_by</code>.
     */
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>physical_examination_system.check_item_info.created_by</code>.
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Getter for <code>physical_examination_system.check_item_info.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Setter for <code>physical_examination_system.check_item_info.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * Getter for <code>physical_examination_system.check_item_info.is_deleted</code>.
     */
    public Integer getIsDeleted() {
        return this.isDeleted;
    }

    /**
     * Setter for <code>physical_examination_system.check_item_info.is_deleted</code>.
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * Getter for <code>physical_examination_system.check_item_info.mode</code>.
     */
    public String getMode() {
        return this.mode;
    }

    /**
     * Setter for <code>physical_examination_system.check_item_info.mode</code>.
     */
    public void setMode(String mode) {
        this.mode = mode;
    }

    /**
     * Getter for <code>physical_examination_system.check_item_info.modified_by</code>.
     */
    public String getModifiedBy() {
        return this.modifiedBy;
    }

    /**
     * Setter for <code>physical_examination_system.check_item_info.modified_by</code>.
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * Getter for <code>physical_examination_system.check_item_info.modified_date</code>.
     */
    public LocalDateTime getModifiedDate() {
        return this.modifiedDate;
    }

    /**
     * Setter for <code>physical_examination_system.check_item_info.modified_date</code>.
     */
    public void setModifiedDate(LocalDateTime modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    /**
     * Getter for <code>physical_examination_system.check_item_info.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>physical_examination_system.check_item_info.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>physical_examination_system.check_item_info.position</code>.
     */
    public String getPosition() {
        return this.position;
    }

    /**
     * Setter for <code>physical_examination_system.check_item_info.position</code>.
     */
    public void setPosition(String position) {
        this.position = position;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CheckItemInfo (");

        sb.append(id);
        sb.append(", ").append(catalogId);
        sb.append(", ").append(code);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(createdDate);
        sb.append(", ").append(isDeleted);
        sb.append(", ").append(mode);
        sb.append(", ").append(modifiedBy);
        sb.append(", ").append(modifiedDate);
        sb.append(", ").append(name);
        sb.append(", ").append(position);

        sb.append(")");
        return sb.toString();
    }
}
