/*
 * This file is generated by jOOQ.
 */
package com.example.boot.data.database.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DeliveryAgencyInfo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private String        code;
    private String        createdBy;
    private LocalDateTime createdDate;
    private Integer       isDeleted;
    private String        modifiedBy;
    private LocalDateTime modifiedDate;
    private String        name;
    private Integer       type;

    public DeliveryAgencyInfo() {}

    public DeliveryAgencyInfo(DeliveryAgencyInfo value) {
        this.id = value.id;
        this.code = value.code;
        this.createdBy = value.createdBy;
        this.createdDate = value.createdDate;
        this.isDeleted = value.isDeleted;
        this.modifiedBy = value.modifiedBy;
        this.modifiedDate = value.modifiedDate;
        this.name = value.name;
        this.type = value.type;
    }

    public DeliveryAgencyInfo(
        Long          id,
        String        code,
        String        createdBy,
        LocalDateTime createdDate,
        Integer       isDeleted,
        String        modifiedBy,
        LocalDateTime modifiedDate,
        String        name,
        Integer       type
    ) {
        this.id = id;
        this.code = code;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.isDeleted = isDeleted;
        this.modifiedBy = modifiedBy;
        this.modifiedDate = modifiedDate;
        this.name = name;
        this.type = type;
    }

    /**
     * Getter for <code>physical_examination_system.delivery_agency_info.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>physical_examination_system.delivery_agency_info.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>physical_examination_system.delivery_agency_info.code</code>.
     */
    public String getCode() {
        return this.code;
    }

    /**
     * Setter for <code>physical_examination_system.delivery_agency_info.code</code>.
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * Getter for <code>physical_examination_system.delivery_agency_info.created_by</code>.
     */
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>physical_examination_system.delivery_agency_info.created_by</code>.
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Getter for <code>physical_examination_system.delivery_agency_info.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Setter for <code>physical_examination_system.delivery_agency_info.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * Getter for <code>physical_examination_system.delivery_agency_info.is_deleted</code>.
     */
    public Integer getIsDeleted() {
        return this.isDeleted;
    }

    /**
     * Setter for <code>physical_examination_system.delivery_agency_info.is_deleted</code>.
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * Getter for <code>physical_examination_system.delivery_agency_info.modified_by</code>.
     */
    public String getModifiedBy() {
        return this.modifiedBy;
    }

    /**
     * Setter for <code>physical_examination_system.delivery_agency_info.modified_by</code>.
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * Getter for <code>physical_examination_system.delivery_agency_info.modified_date</code>.
     */
    public LocalDateTime getModifiedDate() {
        return this.modifiedDate;
    }

    /**
     * Setter for <code>physical_examination_system.delivery_agency_info.modified_date</code>.
     */
    public void setModifiedDate(LocalDateTime modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    /**
     * Getter for <code>physical_examination_system.delivery_agency_info.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>physical_examination_system.delivery_agency_info.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>physical_examination_system.delivery_agency_info.type</code>.
     */
    public Integer getType() {
        return this.type;
    }

    /**
     * Setter for <code>physical_examination_system.delivery_agency_info.type</code>.
     */
    public void setType(Integer type) {
        this.type = type;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DeliveryAgencyInfo (");

        sb.append(id);
        sb.append(", ").append(code);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(createdDate);
        sb.append(", ").append(isDeleted);
        sb.append(", ").append(modifiedBy);
        sb.append(", ").append(modifiedDate);
        sb.append(", ").append(name);
        sb.append(", ").append(type);

        sb.append(")");
        return sb.toString();
    }
}
