/*
 * This file is generated by jOOQ.
 */
package com.example.boot.data.database.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DeliveryAgencyItemInfo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private Long          agencyId;
    private String        checkItemCode;
    private Long          checkItemId;
    private String        checkItemName;
    private String        code;
    private String        createdBy;
    private LocalDateTime createdDate;
    private String        feeItemCode;
    private Long          feeItemId;
    private String        feeItemName;
    private String        interfaceCode;
    private Integer       isDeleted;
    private String        modifiedBy;
    private LocalDateTime modifiedDate;
    private String        name;
    private String        operationMethod;
    private Integer       type;

    public DeliveryAgencyItemInfo() {}

    public DeliveryAgencyItemInfo(DeliveryAgencyItemInfo value) {
        this.id = value.id;
        this.agencyId = value.agencyId;
        this.checkItemCode = value.checkItemCode;
        this.checkItemId = value.checkItemId;
        this.checkItemName = value.checkItemName;
        this.code = value.code;
        this.createdBy = value.createdBy;
        this.createdDate = value.createdDate;
        this.feeItemCode = value.feeItemCode;
        this.feeItemId = value.feeItemId;
        this.feeItemName = value.feeItemName;
        this.interfaceCode = value.interfaceCode;
        this.isDeleted = value.isDeleted;
        this.modifiedBy = value.modifiedBy;
        this.modifiedDate = value.modifiedDate;
        this.name = value.name;
        this.operationMethod = value.operationMethod;
        this.type = value.type;
    }

    public DeliveryAgencyItemInfo(
        Long          id,
        Long          agencyId,
        String        checkItemCode,
        Long          checkItemId,
        String        checkItemName,
        String        code,
        String        createdBy,
        LocalDateTime createdDate,
        String        feeItemCode,
        Long          feeItemId,
        String        feeItemName,
        String        interfaceCode,
        Integer       isDeleted,
        String        modifiedBy,
        LocalDateTime modifiedDate,
        String        name,
        String        operationMethod,
        Integer       type
    ) {
        this.id = id;
        this.agencyId = agencyId;
        this.checkItemCode = checkItemCode;
        this.checkItemId = checkItemId;
        this.checkItemName = checkItemName;
        this.code = code;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.feeItemCode = feeItemCode;
        this.feeItemId = feeItemId;
        this.feeItemName = feeItemName;
        this.interfaceCode = interfaceCode;
        this.isDeleted = isDeleted;
        this.modifiedBy = modifiedBy;
        this.modifiedDate = modifiedDate;
        this.name = name;
        this.operationMethod = operationMethod;
        this.type = type;
    }

    /**
     * Getter for <code>physical_examination_system.delivery_agency_item_info.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>physical_examination_system.delivery_agency_item_info.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>physical_examination_system.delivery_agency_item_info.agency_id</code>.
     */
    public Long getAgencyId() {
        return this.agencyId;
    }

    /**
     * Setter for <code>physical_examination_system.delivery_agency_item_info.agency_id</code>.
     */
    public void setAgencyId(Long agencyId) {
        this.agencyId = agencyId;
    }

    /**
     * Getter for <code>physical_examination_system.delivery_agency_item_info.check_item_code</code>.
     */
    public String getCheckItemCode() {
        return this.checkItemCode;
    }

    /**
     * Setter for <code>physical_examination_system.delivery_agency_item_info.check_item_code</code>.
     */
    public void setCheckItemCode(String checkItemCode) {
        this.checkItemCode = checkItemCode;
    }

    /**
     * Getter for <code>physical_examination_system.delivery_agency_item_info.check_item_id</code>.
     */
    public Long getCheckItemId() {
        return this.checkItemId;
    }

    /**
     * Setter for <code>physical_examination_system.delivery_agency_item_info.check_item_id</code>.
     */
    public void setCheckItemId(Long checkItemId) {
        this.checkItemId = checkItemId;
    }

    /**
     * Getter for <code>physical_examination_system.delivery_agency_item_info.check_item_name</code>.
     */
    public String getCheckItemName() {
        return this.checkItemName;
    }

    /**
     * Setter for <code>physical_examination_system.delivery_agency_item_info.check_item_name</code>.
     */
    public void setCheckItemName(String checkItemName) {
        this.checkItemName = checkItemName;
    }

    /**
     * Getter for <code>physical_examination_system.delivery_agency_item_info.code</code>.
     */
    public String getCode() {
        return this.code;
    }

    /**
     * Setter for <code>physical_examination_system.delivery_agency_item_info.code</code>.
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * Getter for <code>physical_examination_system.delivery_agency_item_info.created_by</code>.
     */
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>physical_examination_system.delivery_agency_item_info.created_by</code>.
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Getter for <code>physical_examination_system.delivery_agency_item_info.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Setter for <code>physical_examination_system.delivery_agency_item_info.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * Getter for <code>physical_examination_system.delivery_agency_item_info.fee_item_code</code>.
     */
    public String getFeeItemCode() {
        return this.feeItemCode;
    }

    /**
     * Setter for <code>physical_examination_system.delivery_agency_item_info.fee_item_code</code>.
     */
    public void setFeeItemCode(String feeItemCode) {
        this.feeItemCode = feeItemCode;
    }

    /**
     * Getter for <code>physical_examination_system.delivery_agency_item_info.fee_item_id</code>.
     */
    public Long getFeeItemId() {
        return this.feeItemId;
    }

    /**
     * Setter for <code>physical_examination_system.delivery_agency_item_info.fee_item_id</code>.
     */
    public void setFeeItemId(Long feeItemId) {
        this.feeItemId = feeItemId;
    }

    /**
     * Getter for <code>physical_examination_system.delivery_agency_item_info.fee_item_name</code>.
     */
    public String getFeeItemName() {
        return this.feeItemName;
    }

    /**
     * Setter for <code>physical_examination_system.delivery_agency_item_info.fee_item_name</code>.
     */
    public void setFeeItemName(String feeItemName) {
        this.feeItemName = feeItemName;
    }

    /**
     * Getter for <code>physical_examination_system.delivery_agency_item_info.interface_code</code>.
     */
    public String getInterfaceCode() {
        return this.interfaceCode;
    }

    /**
     * Setter for <code>physical_examination_system.delivery_agency_item_info.interface_code</code>.
     */
    public void setInterfaceCode(String interfaceCode) {
        this.interfaceCode = interfaceCode;
    }

    /**
     * Getter for <code>physical_examination_system.delivery_agency_item_info.is_deleted</code>.
     */
    public Integer getIsDeleted() {
        return this.isDeleted;
    }

    /**
     * Setter for <code>physical_examination_system.delivery_agency_item_info.is_deleted</code>.
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * Getter for <code>physical_examination_system.delivery_agency_item_info.modified_by</code>.
     */
    public String getModifiedBy() {
        return this.modifiedBy;
    }

    /**
     * Setter for <code>physical_examination_system.delivery_agency_item_info.modified_by</code>.
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * Getter for <code>physical_examination_system.delivery_agency_item_info.modified_date</code>.
     */
    public LocalDateTime getModifiedDate() {
        return this.modifiedDate;
    }

    /**
     * Setter for <code>physical_examination_system.delivery_agency_item_info.modified_date</code>.
     */
    public void setModifiedDate(LocalDateTime modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    /**
     * Getter for <code>physical_examination_system.delivery_agency_item_info.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>physical_examination_system.delivery_agency_item_info.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>physical_examination_system.delivery_agency_item_info.operation_method</code>.
     */
    public String getOperationMethod() {
        return this.operationMethod;
    }

    /**
     * Setter for <code>physical_examination_system.delivery_agency_item_info.operation_method</code>.
     */
    public void setOperationMethod(String operationMethod) {
        this.operationMethod = operationMethod;
    }

    /**
     * Getter for <code>physical_examination_system.delivery_agency_item_info.type</code>.
     */
    public Integer getType() {
        return this.type;
    }

    /**
     * Setter for <code>physical_examination_system.delivery_agency_item_info.type</code>.
     */
    public void setType(Integer type) {
        this.type = type;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DeliveryAgencyItemInfo (");

        sb.append(id);
        sb.append(", ").append(agencyId);
        sb.append(", ").append(checkItemCode);
        sb.append(", ").append(checkItemId);
        sb.append(", ").append(checkItemName);
        sb.append(", ").append(code);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(createdDate);
        sb.append(", ").append(feeItemCode);
        sb.append(", ").append(feeItemId);
        sb.append(", ").append(feeItemName);
        sb.append(", ").append(interfaceCode);
        sb.append(", ").append(isDeleted);
        sb.append(", ").append(modifiedBy);
        sb.append(", ").append(modifiedDate);
        sb.append(", ").append(name);
        sb.append(", ").append(operationMethod);
        sb.append(", ").append(type);

        sb.append(")");
        return sb.toString();
    }
}
