/*
 * This file is generated by jOOQ.
 */
package com.example.boot.data.database.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FeeCheckItemInfo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private Long          checkItemId;
    private String        createdBy;
    private LocalDateTime createdDate;
    private Long          feeItemId;
    private Integer       isDeleted;
    private Integer       isSingle;
    private String        modifiedBy;
    private LocalDateTime modifiedDate;

    public FeeCheckItemInfo() {}

    public FeeCheckItemInfo(FeeCheckItemInfo value) {
        this.id = value.id;
        this.checkItemId = value.checkItemId;
        this.createdBy = value.createdBy;
        this.createdDate = value.createdDate;
        this.feeItemId = value.feeItemId;
        this.isDeleted = value.isDeleted;
        this.isSingle = value.isSingle;
        this.modifiedBy = value.modifiedBy;
        this.modifiedDate = value.modifiedDate;
    }

    public FeeCheckItemInfo(
        Long          id,
        Long          checkItemId,
        String        createdBy,
        LocalDateTime createdDate,
        Long          feeItemId,
        Integer       isDeleted,
        Integer       isSingle,
        String        modifiedBy,
        LocalDateTime modifiedDate
    ) {
        this.id = id;
        this.checkItemId = checkItemId;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.feeItemId = feeItemId;
        this.isDeleted = isDeleted;
        this.isSingle = isSingle;
        this.modifiedBy = modifiedBy;
        this.modifiedDate = modifiedDate;
    }

    /**
     * Getter for <code>physical_examination_system.fee_check_item_info.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>physical_examination_system.fee_check_item_info.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>physical_examination_system.fee_check_item_info.check_item_id</code>.
     */
    public Long getCheckItemId() {
        return this.checkItemId;
    }

    /**
     * Setter for <code>physical_examination_system.fee_check_item_info.check_item_id</code>.
     */
    public void setCheckItemId(Long checkItemId) {
        this.checkItemId = checkItemId;
    }

    /**
     * Getter for <code>physical_examination_system.fee_check_item_info.created_by</code>.
     */
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>physical_examination_system.fee_check_item_info.created_by</code>.
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Getter for <code>physical_examination_system.fee_check_item_info.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Setter for <code>physical_examination_system.fee_check_item_info.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * Getter for <code>physical_examination_system.fee_check_item_info.fee_item_id</code>.
     */
    public Long getFeeItemId() {
        return this.feeItemId;
    }

    /**
     * Setter for <code>physical_examination_system.fee_check_item_info.fee_item_id</code>.
     */
    public void setFeeItemId(Long feeItemId) {
        this.feeItemId = feeItemId;
    }

    /**
     * Getter for <code>physical_examination_system.fee_check_item_info.is_deleted</code>.
     */
    public Integer getIsDeleted() {
        return this.isDeleted;
    }

    /**
     * Setter for <code>physical_examination_system.fee_check_item_info.is_deleted</code>.
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * Getter for <code>physical_examination_system.fee_check_item_info.is_single</code>.
     */
    public Integer getIsSingle() {
        return this.isSingle;
    }

    /**
     * Setter for <code>physical_examination_system.fee_check_item_info.is_single</code>.
     */
    public void setIsSingle(Integer isSingle) {
        this.isSingle = isSingle;
    }

    /**
     * Getter for <code>physical_examination_system.fee_check_item_info.modified_by</code>.
     */
    public String getModifiedBy() {
        return this.modifiedBy;
    }

    /**
     * Setter for <code>physical_examination_system.fee_check_item_info.modified_by</code>.
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * Getter for <code>physical_examination_system.fee_check_item_info.modified_date</code>.
     */
    public LocalDateTime getModifiedDate() {
        return this.modifiedDate;
    }

    /**
     * Setter for <code>physical_examination_system.fee_check_item_info.modified_date</code>.
     */
    public void setModifiedDate(LocalDateTime modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FeeCheckItemInfo (");

        sb.append(id);
        sb.append(", ").append(checkItemId);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(createdDate);
        sb.append(", ").append(feeItemId);
        sb.append(", ").append(isDeleted);
        sb.append(", ").append(isSingle);
        sb.append(", ").append(modifiedBy);
        sb.append(", ").append(modifiedDate);

        sb.append(")");
        return sb.toString();
    }
}
