/*
 * This file is generated by jOOQ.
 */
package com.example.boot.data.database.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MealFeeItemInfo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private String        createdBy;
    private LocalDateTime createdDate;
    private BigDecimal    discountPrice;
    private BigDecimal    discountRate;
    private Long          feeItemId;
    private Integer       isDeleted;
    private Long          mealId;
    private String        modifiedBy;
    private LocalDateTime modifiedDate;
    private BigDecimal    price;

    public MealFeeItemInfo() {}

    public MealFeeItemInfo(MealFeeItemInfo value) {
        this.id = value.id;
        this.createdBy = value.createdBy;
        this.createdDate = value.createdDate;
        this.discountPrice = value.discountPrice;
        this.discountRate = value.discountRate;
        this.feeItemId = value.feeItemId;
        this.isDeleted = value.isDeleted;
        this.mealId = value.mealId;
        this.modifiedBy = value.modifiedBy;
        this.modifiedDate = value.modifiedDate;
        this.price = value.price;
    }

    public MealFeeItemInfo(
        Long          id,
        String        createdBy,
        LocalDateTime createdDate,
        BigDecimal    discountPrice,
        BigDecimal    discountRate,
        Long          feeItemId,
        Integer       isDeleted,
        Long          mealId,
        String        modifiedBy,
        LocalDateTime modifiedDate,
        BigDecimal    price
    ) {
        this.id = id;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.discountPrice = discountPrice;
        this.discountRate = discountRate;
        this.feeItemId = feeItemId;
        this.isDeleted = isDeleted;
        this.mealId = mealId;
        this.modifiedBy = modifiedBy;
        this.modifiedDate = modifiedDate;
        this.price = price;
    }

    /**
     * Getter for <code>physical_examination_system.meal_fee_item_info.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>physical_examination_system.meal_fee_item_info.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>physical_examination_system.meal_fee_item_info.created_by</code>.
     */
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>physical_examination_system.meal_fee_item_info.created_by</code>.
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Getter for <code>physical_examination_system.meal_fee_item_info.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Setter for <code>physical_examination_system.meal_fee_item_info.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * Getter for <code>physical_examination_system.meal_fee_item_info.discount_price</code>.
     */
    public BigDecimal getDiscountPrice() {
        return this.discountPrice;
    }

    /**
     * Setter for <code>physical_examination_system.meal_fee_item_info.discount_price</code>.
     */
    public void setDiscountPrice(BigDecimal discountPrice) {
        this.discountPrice = discountPrice;
    }

    /**
     * Getter for <code>physical_examination_system.meal_fee_item_info.discount_rate</code>.
     */
    public BigDecimal getDiscountRate() {
        return this.discountRate;
    }

    /**
     * Setter for <code>physical_examination_system.meal_fee_item_info.discount_rate</code>.
     */
    public void setDiscountRate(BigDecimal discountRate) {
        this.discountRate = discountRate;
    }

    /**
     * Getter for <code>physical_examination_system.meal_fee_item_info.fee_item_id</code>.
     */
    public Long getFeeItemId() {
        return this.feeItemId;
    }

    /**
     * Setter for <code>physical_examination_system.meal_fee_item_info.fee_item_id</code>.
     */
    public void setFeeItemId(Long feeItemId) {
        this.feeItemId = feeItemId;
    }

    /**
     * Getter for <code>physical_examination_system.meal_fee_item_info.is_deleted</code>.
     */
    public Integer getIsDeleted() {
        return this.isDeleted;
    }

    /**
     * Setter for <code>physical_examination_system.meal_fee_item_info.is_deleted</code>.
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * Getter for <code>physical_examination_system.meal_fee_item_info.meal_id</code>.
     */
    public Long getMealId() {
        return this.mealId;
    }

    /**
     * Setter for <code>physical_examination_system.meal_fee_item_info.meal_id</code>.
     */
    public void setMealId(Long mealId) {
        this.mealId = mealId;
    }

    /**
     * Getter for <code>physical_examination_system.meal_fee_item_info.modified_by</code>.
     */
    public String getModifiedBy() {
        return this.modifiedBy;
    }

    /**
     * Setter for <code>physical_examination_system.meal_fee_item_info.modified_by</code>.
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * Getter for <code>physical_examination_system.meal_fee_item_info.modified_date</code>.
     */
    public LocalDateTime getModifiedDate() {
        return this.modifiedDate;
    }

    /**
     * Setter for <code>physical_examination_system.meal_fee_item_info.modified_date</code>.
     */
    public void setModifiedDate(LocalDateTime modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    /**
     * Getter for <code>physical_examination_system.meal_fee_item_info.price</code>.
     */
    public BigDecimal getPrice() {
        return this.price;
    }

    /**
     * Setter for <code>physical_examination_system.meal_fee_item_info.price</code>.
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MealFeeItemInfo (");

        sb.append(id);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(createdDate);
        sb.append(", ").append(discountPrice);
        sb.append(", ").append(discountRate);
        sb.append(", ").append(feeItemId);
        sb.append(", ").append(isDeleted);
        sb.append(", ").append(mealId);
        sb.append(", ").append(modifiedBy);
        sb.append(", ").append(modifiedDate);
        sb.append(", ").append(price);

        sb.append(")");
        return sb.toString();
    }
}
