/*
 * This file is generated by jOOQ.
 */
package com.example.boot.data.database.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PatientFeeItemInfo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private String        createdBy;
    private LocalDateTime createdDate;
    private String        feeItemCode;
    private Long          feeItemId;
    private String        feeItemName;
    private BigDecimal    feeItemPrice;
    private Integer       feeItemType;
    private Integer       isDeleted;
    private String        mealCode;
    private Long          mealId;
    private String        modifiedBy;
    private LocalDateTime modifiedDate;
    private String        patientExamCode;
    private Long          patientExamId;
    private Long          patientMealId;

    public PatientFeeItemInfo() {}

    public PatientFeeItemInfo(PatientFeeItemInfo value) {
        this.id = value.id;
        this.createdBy = value.createdBy;
        this.createdDate = value.createdDate;
        this.feeItemCode = value.feeItemCode;
        this.feeItemId = value.feeItemId;
        this.feeItemName = value.feeItemName;
        this.feeItemPrice = value.feeItemPrice;
        this.feeItemType = value.feeItemType;
        this.isDeleted = value.isDeleted;
        this.mealCode = value.mealCode;
        this.mealId = value.mealId;
        this.modifiedBy = value.modifiedBy;
        this.modifiedDate = value.modifiedDate;
        this.patientExamCode = value.patientExamCode;
        this.patientExamId = value.patientExamId;
        this.patientMealId = value.patientMealId;
    }

    public PatientFeeItemInfo(
        Long          id,
        String        createdBy,
        LocalDateTime createdDate,
        String        feeItemCode,
        Long          feeItemId,
        String        feeItemName,
        BigDecimal    feeItemPrice,
        Integer       feeItemType,
        Integer       isDeleted,
        String        mealCode,
        Long          mealId,
        String        modifiedBy,
        LocalDateTime modifiedDate,
        String        patientExamCode,
        Long          patientExamId,
        Long          patientMealId
    ) {
        this.id = id;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.feeItemCode = feeItemCode;
        this.feeItemId = feeItemId;
        this.feeItemName = feeItemName;
        this.feeItemPrice = feeItemPrice;
        this.feeItemType = feeItemType;
        this.isDeleted = isDeleted;
        this.mealCode = mealCode;
        this.mealId = mealId;
        this.modifiedBy = modifiedBy;
        this.modifiedDate = modifiedDate;
        this.patientExamCode = patientExamCode;
        this.patientExamId = patientExamId;
        this.patientMealId = patientMealId;
    }

    /**
     * Getter for <code>physical_examination_system.patient_fee_item_info.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>physical_examination_system.patient_fee_item_info.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>physical_examination_system.patient_fee_item_info.created_by</code>.
     */
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>physical_examination_system.patient_fee_item_info.created_by</code>.
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Getter for <code>physical_examination_system.patient_fee_item_info.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Setter for <code>physical_examination_system.patient_fee_item_info.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * Getter for <code>physical_examination_system.patient_fee_item_info.fee_item_code</code>.
     */
    public String getFeeItemCode() {
        return this.feeItemCode;
    }

    /**
     * Setter for <code>physical_examination_system.patient_fee_item_info.fee_item_code</code>.
     */
    public void setFeeItemCode(String feeItemCode) {
        this.feeItemCode = feeItemCode;
    }

    /**
     * Getter for <code>physical_examination_system.patient_fee_item_info.fee_item_id</code>.
     */
    public Long getFeeItemId() {
        return this.feeItemId;
    }

    /**
     * Setter for <code>physical_examination_system.patient_fee_item_info.fee_item_id</code>.
     */
    public void setFeeItemId(Long feeItemId) {
        this.feeItemId = feeItemId;
    }

    /**
     * Getter for <code>physical_examination_system.patient_fee_item_info.fee_item_name</code>.
     */
    public String getFeeItemName() {
        return this.feeItemName;
    }

    /**
     * Setter for <code>physical_examination_system.patient_fee_item_info.fee_item_name</code>.
     */
    public void setFeeItemName(String feeItemName) {
        this.feeItemName = feeItemName;
    }

    /**
     * Getter for <code>physical_examination_system.patient_fee_item_info.fee_item_price</code>.
     */
    public BigDecimal getFeeItemPrice() {
        return this.feeItemPrice;
    }

    /**
     * Setter for <code>physical_examination_system.patient_fee_item_info.fee_item_price</code>.
     */
    public void setFeeItemPrice(BigDecimal feeItemPrice) {
        this.feeItemPrice = feeItemPrice;
    }

    /**
     * Getter for <code>physical_examination_system.patient_fee_item_info.fee_item_type</code>.
     */
    public Integer getFeeItemType() {
        return this.feeItemType;
    }

    /**
     * Setter for <code>physical_examination_system.patient_fee_item_info.fee_item_type</code>.
     */
    public void setFeeItemType(Integer feeItemType) {
        this.feeItemType = feeItemType;
    }

    /**
     * Getter for <code>physical_examination_system.patient_fee_item_info.is_deleted</code>.
     */
    public Integer getIsDeleted() {
        return this.isDeleted;
    }

    /**
     * Setter for <code>physical_examination_system.patient_fee_item_info.is_deleted</code>.
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * Getter for <code>physical_examination_system.patient_fee_item_info.meal_code</code>.
     */
    public String getMealCode() {
        return this.mealCode;
    }

    /**
     * Setter for <code>physical_examination_system.patient_fee_item_info.meal_code</code>.
     */
    public void setMealCode(String mealCode) {
        this.mealCode = mealCode;
    }

    /**
     * Getter for <code>physical_examination_system.patient_fee_item_info.meal_id</code>.
     */
    public Long getMealId() {
        return this.mealId;
    }

    /**
     * Setter for <code>physical_examination_system.patient_fee_item_info.meal_id</code>.
     */
    public void setMealId(Long mealId) {
        this.mealId = mealId;
    }

    /**
     * Getter for <code>physical_examination_system.patient_fee_item_info.modified_by</code>.
     */
    public String getModifiedBy() {
        return this.modifiedBy;
    }

    /**
     * Setter for <code>physical_examination_system.patient_fee_item_info.modified_by</code>.
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * Getter for <code>physical_examination_system.patient_fee_item_info.modified_date</code>.
     */
    public LocalDateTime getModifiedDate() {
        return this.modifiedDate;
    }

    /**
     * Setter for <code>physical_examination_system.patient_fee_item_info.modified_date</code>.
     */
    public void setModifiedDate(LocalDateTime modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    /**
     * Getter for <code>physical_examination_system.patient_fee_item_info.patient_exam_code</code>.
     */
    public String getPatientExamCode() {
        return this.patientExamCode;
    }

    /**
     * Setter for <code>physical_examination_system.patient_fee_item_info.patient_exam_code</code>.
     */
    public void setPatientExamCode(String patientExamCode) {
        this.patientExamCode = patientExamCode;
    }

    /**
     * Getter for <code>physical_examination_system.patient_fee_item_info.patient_exam_id</code>.
     */
    public Long getPatientExamId() {
        return this.patientExamId;
    }

    /**
     * Setter for <code>physical_examination_system.patient_fee_item_info.patient_exam_id</code>.
     */
    public void setPatientExamId(Long patientExamId) {
        this.patientExamId = patientExamId;
    }

    /**
     * Getter for <code>physical_examination_system.patient_fee_item_info.patient_meal_id</code>.
     */
    public Long getPatientMealId() {
        return this.patientMealId;
    }

    /**
     * Setter for <code>physical_examination_system.patient_fee_item_info.patient_meal_id</code>.
     */
    public void setPatientMealId(Long patientMealId) {
        this.patientMealId = patientMealId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PatientFeeItemInfo (");

        sb.append(id);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(createdDate);
        sb.append(", ").append(feeItemCode);
        sb.append(", ").append(feeItemId);
        sb.append(", ").append(feeItemName);
        sb.append(", ").append(feeItemPrice);
        sb.append(", ").append(feeItemType);
        sb.append(", ").append(isDeleted);
        sb.append(", ").append(mealCode);
        sb.append(", ").append(mealId);
        sb.append(", ").append(modifiedBy);
        sb.append(", ").append(modifiedDate);
        sb.append(", ").append(patientExamCode);
        sb.append(", ").append(patientExamId);
        sb.append(", ").append(patientMealId);

        sb.append(")");
        return sb.toString();
    }
}
