/*
 * This file is generated by jOOQ.
 */
package com.example.boot.data.database.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PatientOrdinaryItemInfo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private String        createdBy;
    private LocalDateTime createdDate;
    private Long          feeItemId;
    private Integer       isAbnormal;
    private Integer       isDeleted;
    private Integer       isReference;
    private String        itemCode;
    private Long          itemId;
    private String        itemName;
    private String        modifiedBy;
    private LocalDateTime modifiedDate;
    private Long          patientFeeItemId;
    private String        referenceMax;
    private String        referenceMin;
    private String        result;
    private Integer       resultType;
    private String        unit;

    public PatientOrdinaryItemInfo() {}

    public PatientOrdinaryItemInfo(PatientOrdinaryItemInfo value) {
        this.id = value.id;
        this.createdBy = value.createdBy;
        this.createdDate = value.createdDate;
        this.feeItemId = value.feeItemId;
        this.isAbnormal = value.isAbnormal;
        this.isDeleted = value.isDeleted;
        this.isReference = value.isReference;
        this.itemCode = value.itemCode;
        this.itemId = value.itemId;
        this.itemName = value.itemName;
        this.modifiedBy = value.modifiedBy;
        this.modifiedDate = value.modifiedDate;
        this.patientFeeItemId = value.patientFeeItemId;
        this.referenceMax = value.referenceMax;
        this.referenceMin = value.referenceMin;
        this.result = value.result;
        this.resultType = value.resultType;
        this.unit = value.unit;
    }

    public PatientOrdinaryItemInfo(
        Long          id,
        String        createdBy,
        LocalDateTime createdDate,
        Long          feeItemId,
        Integer       isAbnormal,
        Integer       isDeleted,
        Integer       isReference,
        String        itemCode,
        Long          itemId,
        String        itemName,
        String        modifiedBy,
        LocalDateTime modifiedDate,
        Long          patientFeeItemId,
        String        referenceMax,
        String        referenceMin,
        String        result,
        Integer       resultType,
        String        unit
    ) {
        this.id = id;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.feeItemId = feeItemId;
        this.isAbnormal = isAbnormal;
        this.isDeleted = isDeleted;
        this.isReference = isReference;
        this.itemCode = itemCode;
        this.itemId = itemId;
        this.itemName = itemName;
        this.modifiedBy = modifiedBy;
        this.modifiedDate = modifiedDate;
        this.patientFeeItemId = patientFeeItemId;
        this.referenceMax = referenceMax;
        this.referenceMin = referenceMin;
        this.result = result;
        this.resultType = resultType;
        this.unit = unit;
    }

    /**
     * Getter for <code>physical_examination_system.patient_ordinary_item_info.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>physical_examination_system.patient_ordinary_item_info.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>physical_examination_system.patient_ordinary_item_info.created_by</code>.
     */
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>physical_examination_system.patient_ordinary_item_info.created_by</code>.
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Getter for <code>physical_examination_system.patient_ordinary_item_info.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Setter for <code>physical_examination_system.patient_ordinary_item_info.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * Getter for <code>physical_examination_system.patient_ordinary_item_info.fee_item_id</code>.
     */
    public Long getFeeItemId() {
        return this.feeItemId;
    }

    /**
     * Setter for <code>physical_examination_system.patient_ordinary_item_info.fee_item_id</code>.
     */
    public void setFeeItemId(Long feeItemId) {
        this.feeItemId = feeItemId;
    }

    /**
     * Getter for <code>physical_examination_system.patient_ordinary_item_info.is_abnormal</code>.
     */
    public Integer getIsAbnormal() {
        return this.isAbnormal;
    }

    /**
     * Setter for <code>physical_examination_system.patient_ordinary_item_info.is_abnormal</code>.
     */
    public void setIsAbnormal(Integer isAbnormal) {
        this.isAbnormal = isAbnormal;
    }

    /**
     * Getter for <code>physical_examination_system.patient_ordinary_item_info.is_deleted</code>.
     */
    public Integer getIsDeleted() {
        return this.isDeleted;
    }

    /**
     * Setter for <code>physical_examination_system.patient_ordinary_item_info.is_deleted</code>.
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * Getter for <code>physical_examination_system.patient_ordinary_item_info.is_reference</code>.
     */
    public Integer getIsReference() {
        return this.isReference;
    }

    /**
     * Setter for <code>physical_examination_system.patient_ordinary_item_info.is_reference</code>.
     */
    public void setIsReference(Integer isReference) {
        this.isReference = isReference;
    }

    /**
     * Getter for <code>physical_examination_system.patient_ordinary_item_info.item_code</code>.
     */
    public String getItemCode() {
        return this.itemCode;
    }

    /**
     * Setter for <code>physical_examination_system.patient_ordinary_item_info.item_code</code>.
     */
    public void setItemCode(String itemCode) {
        this.itemCode = itemCode;
    }

    /**
     * Getter for <code>physical_examination_system.patient_ordinary_item_info.item_id</code>.
     */
    public Long getItemId() {
        return this.itemId;
    }

    /**
     * Setter for <code>physical_examination_system.patient_ordinary_item_info.item_id</code>.
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * Getter for <code>physical_examination_system.patient_ordinary_item_info.item_name</code>.
     */
    public String getItemName() {
        return this.itemName;
    }

    /**
     * Setter for <code>physical_examination_system.patient_ordinary_item_info.item_name</code>.
     */
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    /**
     * Getter for <code>physical_examination_system.patient_ordinary_item_info.modified_by</code>.
     */
    public String getModifiedBy() {
        return this.modifiedBy;
    }

    /**
     * Setter for <code>physical_examination_system.patient_ordinary_item_info.modified_by</code>.
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * Getter for <code>physical_examination_system.patient_ordinary_item_info.modified_date</code>.
     */
    public LocalDateTime getModifiedDate() {
        return this.modifiedDate;
    }

    /**
     * Setter for <code>physical_examination_system.patient_ordinary_item_info.modified_date</code>.
     */
    public void setModifiedDate(LocalDateTime modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    /**
     * Getter for <code>physical_examination_system.patient_ordinary_item_info.patient_fee_item_id</code>.
     */
    public Long getPatientFeeItemId() {
        return this.patientFeeItemId;
    }

    /**
     * Setter for <code>physical_examination_system.patient_ordinary_item_info.patient_fee_item_id</code>.
     */
    public void setPatientFeeItemId(Long patientFeeItemId) {
        this.patientFeeItemId = patientFeeItemId;
    }

    /**
     * Getter for <code>physical_examination_system.patient_ordinary_item_info.reference_max</code>.
     */
    public String getReferenceMax() {
        return this.referenceMax;
    }

    /**
     * Setter for <code>physical_examination_system.patient_ordinary_item_info.reference_max</code>.
     */
    public void setReferenceMax(String referenceMax) {
        this.referenceMax = referenceMax;
    }

    /**
     * Getter for <code>physical_examination_system.patient_ordinary_item_info.reference_min</code>.
     */
    public String getReferenceMin() {
        return this.referenceMin;
    }

    /**
     * Setter for <code>physical_examination_system.patient_ordinary_item_info.reference_min</code>.
     */
    public void setReferenceMin(String referenceMin) {
        this.referenceMin = referenceMin;
    }

    /**
     * Getter for <code>physical_examination_system.patient_ordinary_item_info.result</code>.
     */
    public String getResult() {
        return this.result;
    }

    /**
     * Setter for <code>physical_examination_system.patient_ordinary_item_info.result</code>.
     */
    public void setResult(String result) {
        this.result = result;
    }

    /**
     * Getter for <code>physical_examination_system.patient_ordinary_item_info.result_type</code>.
     */
    public Integer getResultType() {
        return this.resultType;
    }

    /**
     * Setter for <code>physical_examination_system.patient_ordinary_item_info.result_type</code>.
     */
    public void setResultType(Integer resultType) {
        this.resultType = resultType;
    }

    /**
     * Getter for <code>physical_examination_system.patient_ordinary_item_info.unit</code>.
     */
    public String getUnit() {
        return this.unit;
    }

    /**
     * Setter for <code>physical_examination_system.patient_ordinary_item_info.unit</code>.
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PatientOrdinaryItemInfo (");

        sb.append(id);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(createdDate);
        sb.append(", ").append(feeItemId);
        sb.append(", ").append(isAbnormal);
        sb.append(", ").append(isDeleted);
        sb.append(", ").append(isReference);
        sb.append(", ").append(itemCode);
        sb.append(", ").append(itemId);
        sb.append(", ").append(itemName);
        sb.append(", ").append(modifiedBy);
        sb.append(", ").append(modifiedDate);
        sb.append(", ").append(patientFeeItemId);
        sb.append(", ").append(referenceMax);
        sb.append(", ").append(referenceMin);
        sb.append(", ").append(result);
        sb.append(", ").append(resultType);
        sb.append(", ").append(unit);

        sb.append(")");
        return sb.toString();
    }
}
