/*
 * This file is generated by jOOQ.
 */
package com.example.boot.data.database.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 预约排期
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScheduleAppointmentInfo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private LocalDateTime createdDate;
    private LocalDateTime modifiedDate;
    private String        createdBy;
    private String        modifiedBy;
    private Integer       isDeleted;
    private LocalDateTime appointmentDate;
    private LocalDateTime appointmentCycle;
    private Integer       appointmentType;
    private Integer       isEnable;

    public ScheduleAppointmentInfo() {}

    public ScheduleAppointmentInfo(ScheduleAppointmentInfo value) {
        this.id = value.id;
        this.createdDate = value.createdDate;
        this.modifiedDate = value.modifiedDate;
        this.createdBy = value.createdBy;
        this.modifiedBy = value.modifiedBy;
        this.isDeleted = value.isDeleted;
        this.appointmentDate = value.appointmentDate;
        this.appointmentCycle = value.appointmentCycle;
        this.appointmentType = value.appointmentType;
        this.isEnable = value.isEnable;
    }

    public ScheduleAppointmentInfo(
        Long          id,
        LocalDateTime createdDate,
        LocalDateTime modifiedDate,
        String        createdBy,
        String        modifiedBy,
        Integer       isDeleted,
        LocalDateTime appointmentDate,
        LocalDateTime appointmentCycle,
        Integer       appointmentType,
        Integer       isEnable
    ) {
        this.id = id;
        this.createdDate = createdDate;
        this.modifiedDate = modifiedDate;
        this.createdBy = createdBy;
        this.modifiedBy = modifiedBy;
        this.isDeleted = isDeleted;
        this.appointmentDate = appointmentDate;
        this.appointmentCycle = appointmentCycle;
        this.appointmentType = appointmentType;
        this.isEnable = isEnable;
    }

    /**
     * Getter for <code>physical_examination_system.schedule_appointment_info.id</code>. id
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>physical_examination_system.schedule_appointment_info.id</code>. id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>physical_examination_system.schedule_appointment_info.created_date</code>. createdDate
     */
    public LocalDateTime getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Setter for <code>physical_examination_system.schedule_appointment_info.created_date</code>. createdDate
     */
    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * Getter for <code>physical_examination_system.schedule_appointment_info.modified_date</code>. modifiedDate
     */
    public LocalDateTime getModifiedDate() {
        return this.modifiedDate;
    }

    /**
     * Setter for <code>physical_examination_system.schedule_appointment_info.modified_date</code>. modifiedDate
     */
    public void setModifiedDate(LocalDateTime modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    /**
     * Getter for <code>physical_examination_system.schedule_appointment_info.created_by</code>. createdBy
     */
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>physical_examination_system.schedule_appointment_info.created_by</code>. createdBy
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Getter for <code>physical_examination_system.schedule_appointment_info.modified_by</code>. modifiedBy
     */
    public String getModifiedBy() {
        return this.modifiedBy;
    }

    /**
     * Setter for <code>physical_examination_system.schedule_appointment_info.modified_by</code>. modifiedBy
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * Getter for <code>physical_examination_system.schedule_appointment_info.is_deleted</code>. isDeleted
     */
    public Integer getIsDeleted() {
        return this.isDeleted;
    }

    /**
     * Setter for <code>physical_examination_system.schedule_appointment_info.is_deleted</code>. isDeleted
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * Getter for <code>physical_examination_system.schedule_appointment_info.appointment_date</code>. 预约日期
     */
    public LocalDateTime getAppointmentDate() {
        return this.appointmentDate;
    }

    /**
     * Setter for <code>physical_examination_system.schedule_appointment_info.appointment_date</code>. 预约日期
     */
    public void setAppointmentDate(LocalDateTime appointmentDate) {
        this.appointmentDate = appointmentDate;
    }

    /**
     * Getter for <code>physical_examination_system.schedule_appointment_info.appointment_cycle</code>. 预约区间
     * 1 全天 2 上午 3 下午
     */
    public LocalDateTime getAppointmentCycle() {
        return this.appointmentCycle;
    }

    /**
     * Setter for <code>physical_examination_system.schedule_appointment_info.appointment_cycle</code>. 预约区间
     * 1 全天 2 上午 3 下午
     */
    public void setAppointmentCycle(LocalDateTime appointmentCycle) {
        this.appointmentCycle = appointmentCycle;
    }

    /**
     * Getter for <code>physical_examination_system.schedule_appointment_info.appointment_type</code>. 预约类型
     * 1 个人 2 团队 3 总数
     */
    public Integer getAppointmentType() {
        return this.appointmentType;
    }

    /**
     * Setter for <code>physical_examination_system.schedule_appointment_info.appointment_type</code>. 预约类型
     * 1 个人 2 团队 3 总数
     */
    public void setAppointmentType(Integer appointmentType) {
        this.appointmentType = appointmentType;
    }

    /**
     * Getter for <code>physical_examination_system.schedule_appointment_info.is_enable</code>. 是否启用
     * 1 是 0 否
     */
    public Integer getIsEnable() {
        return this.isEnable;
    }

    /**
     * Setter for <code>physical_examination_system.schedule_appointment_info.is_enable</code>. 是否启用
     * 1 是 0 否
     */
    public void setIsEnable(Integer isEnable) {
        this.isEnable = isEnable;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ScheduleAppointmentInfo (");

        sb.append(id);
        sb.append(", ").append(createdDate);
        sb.append(", ").append(modifiedDate);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(modifiedBy);
        sb.append(", ").append(isDeleted);
        sb.append(", ").append(appointmentDate);
        sb.append(", ").append(appointmentCycle);
        sb.append(", ").append(appointmentType);
        sb.append(", ").append(isEnable);

        sb.append(")");
        return sb.toString();
    }
}
