/*
 * This file is generated by jOOQ.
 */
package com.example.boot.data.database.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * system_permission_info
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SystemPermissionInfo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private LocalDateTime createdDate;
    private LocalDateTime modifiedDate;
    private String        createdBy;
    private String        modifiedBy;
    private Integer       isDeleted;
    private String        name;
    private String        module;
    private String        fullName;
    private Integer       level;
    private Integer       isEnabled;

    public SystemPermissionInfo() {}

    public SystemPermissionInfo(SystemPermissionInfo value) {
        this.id = value.id;
        this.createdDate = value.createdDate;
        this.modifiedDate = value.modifiedDate;
        this.createdBy = value.createdBy;
        this.modifiedBy = value.modifiedBy;
        this.isDeleted = value.isDeleted;
        this.name = value.name;
        this.module = value.module;
        this.fullName = value.fullName;
        this.level = value.level;
        this.isEnabled = value.isEnabled;
    }

    public SystemPermissionInfo(
        Long          id,
        LocalDateTime createdDate,
        LocalDateTime modifiedDate,
        String        createdBy,
        String        modifiedBy,
        Integer       isDeleted,
        String        name,
        String        module,
        String        fullName,
        Integer       level,
        Integer       isEnabled
    ) {
        this.id = id;
        this.createdDate = createdDate;
        this.modifiedDate = modifiedDate;
        this.createdBy = createdBy;
        this.modifiedBy = modifiedBy;
        this.isDeleted = isDeleted;
        this.name = name;
        this.module = module;
        this.fullName = fullName;
        this.level = level;
        this.isEnabled = isEnabled;
    }

    /**
     * Getter for <code>physical_examination_system.system_permission_info.id</code>. id
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>physical_examination_system.system_permission_info.id</code>. id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>physical_examination_system.system_permission_info.created_date</code>. createdDate
     */
    public LocalDateTime getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Setter for <code>physical_examination_system.system_permission_info.created_date</code>. createdDate
     */
    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * Getter for <code>physical_examination_system.system_permission_info.modified_date</code>. modifiedDate
     */
    public LocalDateTime getModifiedDate() {
        return this.modifiedDate;
    }

    /**
     * Setter for <code>physical_examination_system.system_permission_info.modified_date</code>. modifiedDate
     */
    public void setModifiedDate(LocalDateTime modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    /**
     * Getter for <code>physical_examination_system.system_permission_info.created_by</code>. createdBy
     */
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>physical_examination_system.system_permission_info.created_by</code>. createdBy
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Getter for <code>physical_examination_system.system_permission_info.modified_by</code>. modifiedBy
     */
    public String getModifiedBy() {
        return this.modifiedBy;
    }

    /**
     * Setter for <code>physical_examination_system.system_permission_info.modified_by</code>. modifiedBy
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * Getter for <code>physical_examination_system.system_permission_info.is_deleted</code>. isDeleted
     */
    public Integer getIsDeleted() {
        return this.isDeleted;
    }

    /**
     * Setter for <code>physical_examination_system.system_permission_info.is_deleted</code>. isDeleted
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * Getter for <code>physical_examination_system.system_permission_info.name</code>. 权限名称
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>physical_examination_system.system_permission_info.name</code>. 权限名称
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>physical_examination_system.system_permission_info.module</code>. 模块名称
     */
    public String getModule() {
        return this.module;
    }

    /**
     * Setter for <code>physical_examination_system.system_permission_info.module</code>. 模块名称
     */
    public void setModule(String module) {
        this.module = module;
    }

    /**
     * Getter for <code>physical_examination_system.system_permission_info.full_name</code>. 全名称
     * 模块名称:权限名称
     */
    public String getFullName() {
        return this.fullName;
    }

    /**
     * Setter for <code>physical_examination_system.system_permission_info.full_name</code>. 全名称
     * 模块名称:权限名称
     */
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    /**
     * Getter for <code>physical_examination_system.system_permission_info.level</code>. 排序
     */
    public Integer getLevel() {
        return this.level;
    }

    /**
     * Setter for <code>physical_examination_system.system_permission_info.level</code>. 排序
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * Getter for <code>physical_examination_system.system_permission_info.is_enabled</code>. 是否启用
     * 0 否 1 是
     */
    public Integer getIsEnabled() {
        return this.isEnabled;
    }

    /**
     * Setter for <code>physical_examination_system.system_permission_info.is_enabled</code>. 是否启用
     * 0 否 1 是
     */
    public void setIsEnabled(Integer isEnabled) {
        this.isEnabled = isEnabled;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SystemPermissionInfo (");

        sb.append(id);
        sb.append(", ").append(createdDate);
        sb.append(", ").append(modifiedDate);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(modifiedBy);
        sb.append(", ").append(isDeleted);
        sb.append(", ").append(name);
        sb.append(", ").append(module);
        sb.append(", ").append(fullName);
        sb.append(", ").append(level);
        sb.append(", ").append(isEnabled);

        sb.append(")");
        return sb.toString();
    }
}
