/*
 * This file is generated by jOOQ.
 */
package com.example.boot.data.database.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SystemPositionInfo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private String        createdBy;
    private LocalDateTime createdDate;
    private String        fullName;
    private Integer       isDeleted;
    private Integer       isEnabled;
    private Integer       level;
    private String        modifiedBy;
    private LocalDateTime modifiedDate;
    private String        module;
    private String        name;
    private String        code;
    private String        description;

    public SystemPositionInfo() {}

    public SystemPositionInfo(SystemPositionInfo value) {
        this.id = value.id;
        this.createdBy = value.createdBy;
        this.createdDate = value.createdDate;
        this.fullName = value.fullName;
        this.isDeleted = value.isDeleted;
        this.isEnabled = value.isEnabled;
        this.level = value.level;
        this.modifiedBy = value.modifiedBy;
        this.modifiedDate = value.modifiedDate;
        this.module = value.module;
        this.name = value.name;
        this.code = value.code;
        this.description = value.description;
    }

    public SystemPositionInfo(
        Long          id,
        String        createdBy,
        LocalDateTime createdDate,
        String        fullName,
        Integer       isDeleted,
        Integer       isEnabled,
        Integer       level,
        String        modifiedBy,
        LocalDateTime modifiedDate,
        String        module,
        String        name,
        String        code,
        String        description
    ) {
        this.id = id;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.fullName = fullName;
        this.isDeleted = isDeleted;
        this.isEnabled = isEnabled;
        this.level = level;
        this.modifiedBy = modifiedBy;
        this.modifiedDate = modifiedDate;
        this.module = module;
        this.name = name;
        this.code = code;
        this.description = description;
    }

    /**
     * Getter for <code>physical_examination_system.system_position_info.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>physical_examination_system.system_position_info.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>physical_examination_system.system_position_info.created_by</code>.
     */
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>physical_examination_system.system_position_info.created_by</code>.
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Getter for <code>physical_examination_system.system_position_info.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Setter for <code>physical_examination_system.system_position_info.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * Getter for <code>physical_examination_system.system_position_info.full_name</code>.
     */
    public String getFullName() {
        return this.fullName;
    }

    /**
     * Setter for <code>physical_examination_system.system_position_info.full_name</code>.
     */
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    /**
     * Getter for <code>physical_examination_system.system_position_info.is_deleted</code>.
     */
    public Integer getIsDeleted() {
        return this.isDeleted;
    }

    /**
     * Setter for <code>physical_examination_system.system_position_info.is_deleted</code>.
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * Getter for <code>physical_examination_system.system_position_info.is_enabled</code>.
     */
    public Integer getIsEnabled() {
        return this.isEnabled;
    }

    /**
     * Setter for <code>physical_examination_system.system_position_info.is_enabled</code>.
     */
    public void setIsEnabled(Integer isEnabled) {
        this.isEnabled = isEnabled;
    }

    /**
     * Getter for <code>physical_examination_system.system_position_info.level</code>.
     */
    public Integer getLevel() {
        return this.level;
    }

    /**
     * Setter for <code>physical_examination_system.system_position_info.level</code>.
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * Getter for <code>physical_examination_system.system_position_info.modified_by</code>.
     */
    public String getModifiedBy() {
        return this.modifiedBy;
    }

    /**
     * Setter for <code>physical_examination_system.system_position_info.modified_by</code>.
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * Getter for <code>physical_examination_system.system_position_info.modified_date</code>.
     */
    public LocalDateTime getModifiedDate() {
        return this.modifiedDate;
    }

    /**
     * Setter for <code>physical_examination_system.system_position_info.modified_date</code>.
     */
    public void setModifiedDate(LocalDateTime modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    /**
     * Getter for <code>physical_examination_system.system_position_info.module</code>.
     */
    public String getModule() {
        return this.module;
    }

    /**
     * Setter for <code>physical_examination_system.system_position_info.module</code>.
     */
    public void setModule(String module) {
        this.module = module;
    }

    /**
     * Getter for <code>physical_examination_system.system_position_info.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>physical_examination_system.system_position_info.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>physical_examination_system.system_position_info.code</code>.
     */
    public String getCode() {
        return this.code;
    }

    /**
     * Setter for <code>physical_examination_system.system_position_info.code</code>.
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * Getter for <code>physical_examination_system.system_position_info.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>physical_examination_system.system_position_info.description</code>.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SystemPositionInfo (");

        sb.append(id);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(createdDate);
        sb.append(", ").append(fullName);
        sb.append(", ").append(isDeleted);
        sb.append(", ").append(isEnabled);
        sb.append(", ").append(level);
        sb.append(", ").append(modifiedBy);
        sb.append(", ").append(modifiedDate);
        sb.append(", ").append(module);
        sb.append(", ").append(name);
        sb.append(", ").append(code);
        sb.append(", ").append(description);

        sb.append(")");
        return sb.toString();
    }
}
