/*
 * This file is generated by jOOQ.
 */
package com.example.boot.data.database.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SystemUsersInfo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private String        createdBy;
    private LocalDateTime createdDate;
    private Integer       isDeleted;
    private Integer       isEnabled;
    private String        modifiedBy;
    private LocalDateTime modifiedDate;
    private String        name;
    private String        password;
    private String        username;
    private String        phone;

    public SystemUsersInfo() {}

    public SystemUsersInfo(SystemUsersInfo value) {
        this.id = value.id;
        this.createdBy = value.createdBy;
        this.createdDate = value.createdDate;
        this.isDeleted = value.isDeleted;
        this.isEnabled = value.isEnabled;
        this.modifiedBy = value.modifiedBy;
        this.modifiedDate = value.modifiedDate;
        this.name = value.name;
        this.password = value.password;
        this.username = value.username;
        this.phone = value.phone;
    }

    public SystemUsersInfo(
        Long          id,
        String        createdBy,
        LocalDateTime createdDate,
        Integer       isDeleted,
        Integer       isEnabled,
        String        modifiedBy,
        LocalDateTime modifiedDate,
        String        name,
        String        password,
        String        username,
        String        phone
    ) {
        this.id = id;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.isDeleted = isDeleted;
        this.isEnabled = isEnabled;
        this.modifiedBy = modifiedBy;
        this.modifiedDate = modifiedDate;
        this.name = name;
        this.password = password;
        this.username = username;
        this.phone = phone;
    }

    /**
     * Getter for <code>physical_examination_system.system_users_info.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>physical_examination_system.system_users_info.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>physical_examination_system.system_users_info.created_by</code>.
     */
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>physical_examination_system.system_users_info.created_by</code>.
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Getter for <code>physical_examination_system.system_users_info.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Setter for <code>physical_examination_system.system_users_info.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * Getter for <code>physical_examination_system.system_users_info.is_deleted</code>.
     */
    public Integer getIsDeleted() {
        return this.isDeleted;
    }

    /**
     * Setter for <code>physical_examination_system.system_users_info.is_deleted</code>.
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * Getter for <code>physical_examination_system.system_users_info.is_enabled</code>.
     */
    public Integer getIsEnabled() {
        return this.isEnabled;
    }

    /**
     * Setter for <code>physical_examination_system.system_users_info.is_enabled</code>.
     */
    public void setIsEnabled(Integer isEnabled) {
        this.isEnabled = isEnabled;
    }

    /**
     * Getter for <code>physical_examination_system.system_users_info.modified_by</code>.
     */
    public String getModifiedBy() {
        return this.modifiedBy;
    }

    /**
     * Setter for <code>physical_examination_system.system_users_info.modified_by</code>.
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * Getter for <code>physical_examination_system.system_users_info.modified_date</code>.
     */
    public LocalDateTime getModifiedDate() {
        return this.modifiedDate;
    }

    /**
     * Setter for <code>physical_examination_system.system_users_info.modified_date</code>.
     */
    public void setModifiedDate(LocalDateTime modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    /**
     * Getter for <code>physical_examination_system.system_users_info.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>physical_examination_system.system_users_info.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>physical_examination_system.system_users_info.password</code>.
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * Setter for <code>physical_examination_system.system_users_info.password</code>.
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Getter for <code>physical_examination_system.system_users_info.username</code>.
     */
    public String getUsername() {
        return this.username;
    }

    /**
     * Setter for <code>physical_examination_system.system_users_info.username</code>.
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Getter for <code>physical_examination_system.system_users_info.phone</code>.
     */
    public String getPhone() {
        return this.phone;
    }

    /**
     * Setter for <code>physical_examination_system.system_users_info.phone</code>.
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SystemUsersInfo (");

        sb.append(id);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(createdDate);
        sb.append(", ").append(isDeleted);
        sb.append(", ").append(isEnabled);
        sb.append(", ").append(modifiedBy);
        sb.append(", ").append(modifiedDate);
        sb.append(", ").append(name);
        sb.append(", ").append(password);
        sb.append(", ").append(username);
        sb.append(", ").append(phone);

        sb.append(")");
        return sb.toString();
    }
}
