/*
 * This file is generated by jOOQ.
 */
package com.example.boot.data.database.jooq.tables.records;


import com.example.boot.data.database.jooq.tables.CheckItemInfo;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CheckItemInfoRecord extends UpdatableRecordImpl<CheckItemInfoRecord> implements Record11<Long, Long, String, String, LocalDateTime, Integer, String, String, LocalDateTime, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>physical_examination_system.check_item_info.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>physical_examination_system.check_item_info.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>physical_examination_system.check_item_info.catalog_id</code>.
     */
    public void setCatalogId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>physical_examination_system.check_item_info.catalog_id</code>.
     */
    public Long getCatalogId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>physical_examination_system.check_item_info.code</code>.
     */
    public void setCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>physical_examination_system.check_item_info.code</code>.
     */
    public String getCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>physical_examination_system.check_item_info.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>physical_examination_system.check_item_info.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(3);
    }

    /**
     * Setter for <code>physical_examination_system.check_item_info.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>physical_examination_system.check_item_info.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>physical_examination_system.check_item_info.is_deleted</code>.
     */
    public void setIsDeleted(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>physical_examination_system.check_item_info.is_deleted</code>.
     */
    public Integer getIsDeleted() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>physical_examination_system.check_item_info.mode</code>.
     */
    public void setMode(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>physical_examination_system.check_item_info.mode</code>.
     */
    public String getMode() {
        return (String) get(6);
    }

    /**
     * Setter for <code>physical_examination_system.check_item_info.modified_by</code>.
     */
    public void setModifiedBy(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>physical_examination_system.check_item_info.modified_by</code>.
     */
    public String getModifiedBy() {
        return (String) get(7);
    }

    /**
     * Setter for <code>physical_examination_system.check_item_info.modified_date</code>.
     */
    public void setModifiedDate(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>physical_examination_system.check_item_info.modified_date</code>.
     */
    public LocalDateTime getModifiedDate() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>physical_examination_system.check_item_info.name</code>.
     */
    public void setName(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>physical_examination_system.check_item_info.name</code>.
     */
    public String getName() {
        return (String) get(9);
    }

    /**
     * Setter for <code>physical_examination_system.check_item_info.position</code>.
     */
    public void setPosition(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>physical_examination_system.check_item_info.position</code>.
     */
    public String getPosition() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<Long, Long, String, String, LocalDateTime, Integer, String, String, LocalDateTime, String, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<Long, Long, String, String, LocalDateTime, Integer, String, String, LocalDateTime, String, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return CheckItemInfo.CHECK_ITEM_INFO.ID;
    }

    @Override
    public Field<Long> field2() {
        return CheckItemInfo.CHECK_ITEM_INFO.CATALOG_ID;
    }

    @Override
    public Field<String> field3() {
        return CheckItemInfo.CHECK_ITEM_INFO.CODE;
    }

    @Override
    public Field<String> field4() {
        return CheckItemInfo.CHECK_ITEM_INFO.CREATED_BY;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return CheckItemInfo.CHECK_ITEM_INFO.CREATED_DATE;
    }

    @Override
    public Field<Integer> field6() {
        return CheckItemInfo.CHECK_ITEM_INFO.IS_DELETED;
    }

    @Override
    public Field<String> field7() {
        return CheckItemInfo.CHECK_ITEM_INFO.MODE;
    }

    @Override
    public Field<String> field8() {
        return CheckItemInfo.CHECK_ITEM_INFO.MODIFIED_BY;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return CheckItemInfo.CHECK_ITEM_INFO.MODIFIED_DATE;
    }

    @Override
    public Field<String> field10() {
        return CheckItemInfo.CHECK_ITEM_INFO.NAME;
    }

    @Override
    public Field<String> field11() {
        return CheckItemInfo.CHECK_ITEM_INFO.POSITION;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getCatalogId();
    }

    @Override
    public String component3() {
        return getCode();
    }

    @Override
    public String component4() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedDate();
    }

    @Override
    public Integer component6() {
        return getIsDeleted();
    }

    @Override
    public String component7() {
        return getMode();
    }

    @Override
    public String component8() {
        return getModifiedBy();
    }

    @Override
    public LocalDateTime component9() {
        return getModifiedDate();
    }

    @Override
    public String component10() {
        return getName();
    }

    @Override
    public String component11() {
        return getPosition();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getCatalogId();
    }

    @Override
    public String value3() {
        return getCode();
    }

    @Override
    public String value4() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedDate();
    }

    @Override
    public Integer value6() {
        return getIsDeleted();
    }

    @Override
    public String value7() {
        return getMode();
    }

    @Override
    public String value8() {
        return getModifiedBy();
    }

    @Override
    public LocalDateTime value9() {
        return getModifiedDate();
    }

    @Override
    public String value10() {
        return getName();
    }

    @Override
    public String value11() {
        return getPosition();
    }

    @Override
    public CheckItemInfoRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public CheckItemInfoRecord value2(Long value) {
        setCatalogId(value);
        return this;
    }

    @Override
    public CheckItemInfoRecord value3(String value) {
        setCode(value);
        return this;
    }

    @Override
    public CheckItemInfoRecord value4(String value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public CheckItemInfoRecord value5(LocalDateTime value) {
        setCreatedDate(value);
        return this;
    }

    @Override
    public CheckItemInfoRecord value6(Integer value) {
        setIsDeleted(value);
        return this;
    }

    @Override
    public CheckItemInfoRecord value7(String value) {
        setMode(value);
        return this;
    }

    @Override
    public CheckItemInfoRecord value8(String value) {
        setModifiedBy(value);
        return this;
    }

    @Override
    public CheckItemInfoRecord value9(LocalDateTime value) {
        setModifiedDate(value);
        return this;
    }

    @Override
    public CheckItemInfoRecord value10(String value) {
        setName(value);
        return this;
    }

    @Override
    public CheckItemInfoRecord value11(String value) {
        setPosition(value);
        return this;
    }

    @Override
    public CheckItemInfoRecord values(Long value1, Long value2, String value3, String value4, LocalDateTime value5, Integer value6, String value7, String value8, LocalDateTime value9, String value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CheckItemInfoRecord
     */
    public CheckItemInfoRecord() {
        super(CheckItemInfo.CHECK_ITEM_INFO);
    }

    /**
     * Create a detached, initialised CheckItemInfoRecord
     */
    public CheckItemInfoRecord(Long id, Long catalogId, String code, String createdBy, LocalDateTime createdDate, Integer isDeleted, String mode, String modifiedBy, LocalDateTime modifiedDate, String name, String position) {
        super(CheckItemInfo.CHECK_ITEM_INFO);

        setId(id);
        setCatalogId(catalogId);
        setCode(code);
        setCreatedBy(createdBy);
        setCreatedDate(createdDate);
        setIsDeleted(isDeleted);
        setMode(mode);
        setModifiedBy(modifiedBy);
        setModifiedDate(modifiedDate);
        setName(name);
        setPosition(position);
    }
}
