/*
 * This file is generated by jOOQ.
 */
package com.example.boot.data.database.jooq.tables.records;


import com.example.boot.data.database.jooq.tables.DeliveryAgencyItemInfo;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record18;
import org.jooq.Row18;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DeliveryAgencyItemInfoRecord extends UpdatableRecordImpl<DeliveryAgencyItemInfoRecord> implements Record18<Long, Long, String, Long, String, String, String, LocalDateTime, String, Long, String, String, Integer, String, LocalDateTime, String, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>physical_examination_system.delivery_agency_item_info.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>physical_examination_system.delivery_agency_item_info.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>physical_examination_system.delivery_agency_item_info.agency_id</code>.
     */
    public void setAgencyId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>physical_examination_system.delivery_agency_item_info.agency_id</code>.
     */
    public Long getAgencyId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>physical_examination_system.delivery_agency_item_info.check_item_code</code>.
     */
    public void setCheckItemCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>physical_examination_system.delivery_agency_item_info.check_item_code</code>.
     */
    public String getCheckItemCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>physical_examination_system.delivery_agency_item_info.check_item_id</code>.
     */
    public void setCheckItemId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>physical_examination_system.delivery_agency_item_info.check_item_id</code>.
     */
    public Long getCheckItemId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>physical_examination_system.delivery_agency_item_info.check_item_name</code>.
     */
    public void setCheckItemName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>physical_examination_system.delivery_agency_item_info.check_item_name</code>.
     */
    public String getCheckItemName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>physical_examination_system.delivery_agency_item_info.code</code>.
     */
    public void setCode(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>physical_examination_system.delivery_agency_item_info.code</code>.
     */
    public String getCode() {
        return (String) get(5);
    }

    /**
     * Setter for <code>physical_examination_system.delivery_agency_item_info.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>physical_examination_system.delivery_agency_item_info.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(6);
    }

    /**
     * Setter for <code>physical_examination_system.delivery_agency_item_info.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>physical_examination_system.delivery_agency_item_info.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>physical_examination_system.delivery_agency_item_info.fee_item_code</code>.
     */
    public void setFeeItemCode(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>physical_examination_system.delivery_agency_item_info.fee_item_code</code>.
     */
    public String getFeeItemCode() {
        return (String) get(8);
    }

    /**
     * Setter for <code>physical_examination_system.delivery_agency_item_info.fee_item_id</code>.
     */
    public void setFeeItemId(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>physical_examination_system.delivery_agency_item_info.fee_item_id</code>.
     */
    public Long getFeeItemId() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>physical_examination_system.delivery_agency_item_info.fee_item_name</code>.
     */
    public void setFeeItemName(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>physical_examination_system.delivery_agency_item_info.fee_item_name</code>.
     */
    public String getFeeItemName() {
        return (String) get(10);
    }

    /**
     * Setter for <code>physical_examination_system.delivery_agency_item_info.interface_code</code>.
     */
    public void setInterfaceCode(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>physical_examination_system.delivery_agency_item_info.interface_code</code>.
     */
    public String getInterfaceCode() {
        return (String) get(11);
    }

    /**
     * Setter for <code>physical_examination_system.delivery_agency_item_info.is_deleted</code>.
     */
    public void setIsDeleted(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>physical_examination_system.delivery_agency_item_info.is_deleted</code>.
     */
    public Integer getIsDeleted() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>physical_examination_system.delivery_agency_item_info.modified_by</code>.
     */
    public void setModifiedBy(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>physical_examination_system.delivery_agency_item_info.modified_by</code>.
     */
    public String getModifiedBy() {
        return (String) get(13);
    }

    /**
     * Setter for <code>physical_examination_system.delivery_agency_item_info.modified_date</code>.
     */
    public void setModifiedDate(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>physical_examination_system.delivery_agency_item_info.modified_date</code>.
     */
    public LocalDateTime getModifiedDate() {
        return (LocalDateTime) get(14);
    }

    /**
     * Setter for <code>physical_examination_system.delivery_agency_item_info.name</code>.
     */
    public void setName(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>physical_examination_system.delivery_agency_item_info.name</code>.
     */
    public String getName() {
        return (String) get(15);
    }

    /**
     * Setter for <code>physical_examination_system.delivery_agency_item_info.operation_method</code>.
     */
    public void setOperationMethod(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>physical_examination_system.delivery_agency_item_info.operation_method</code>.
     */
    public String getOperationMethod() {
        return (String) get(16);
    }

    /**
     * Setter for <code>physical_examination_system.delivery_agency_item_info.type</code>.
     */
    public void setType(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>physical_examination_system.delivery_agency_item_info.type</code>.
     */
    public Integer getType() {
        return (Integer) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record18 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row18<Long, Long, String, Long, String, String, String, LocalDateTime, String, Long, String, String, Integer, String, LocalDateTime, String, String, Integer> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    @Override
    public Row18<Long, Long, String, Long, String, String, String, LocalDateTime, String, Long, String, String, Integer, String, LocalDateTime, String, String, Integer> valuesRow() {
        return (Row18) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return DeliveryAgencyItemInfo.DELIVERY_AGENCY_ITEM_INFO.ID;
    }

    @Override
    public Field<Long> field2() {
        return DeliveryAgencyItemInfo.DELIVERY_AGENCY_ITEM_INFO.AGENCY_ID;
    }

    @Override
    public Field<String> field3() {
        return DeliveryAgencyItemInfo.DELIVERY_AGENCY_ITEM_INFO.CHECK_ITEM_CODE;
    }

    @Override
    public Field<Long> field4() {
        return DeliveryAgencyItemInfo.DELIVERY_AGENCY_ITEM_INFO.CHECK_ITEM_ID;
    }

    @Override
    public Field<String> field5() {
        return DeliveryAgencyItemInfo.DELIVERY_AGENCY_ITEM_INFO.CHECK_ITEM_NAME;
    }

    @Override
    public Field<String> field6() {
        return DeliveryAgencyItemInfo.DELIVERY_AGENCY_ITEM_INFO.CODE;
    }

    @Override
    public Field<String> field7() {
        return DeliveryAgencyItemInfo.DELIVERY_AGENCY_ITEM_INFO.CREATED_BY;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return DeliveryAgencyItemInfo.DELIVERY_AGENCY_ITEM_INFO.CREATED_DATE;
    }

    @Override
    public Field<String> field9() {
        return DeliveryAgencyItemInfo.DELIVERY_AGENCY_ITEM_INFO.FEE_ITEM_CODE;
    }

    @Override
    public Field<Long> field10() {
        return DeliveryAgencyItemInfo.DELIVERY_AGENCY_ITEM_INFO.FEE_ITEM_ID;
    }

    @Override
    public Field<String> field11() {
        return DeliveryAgencyItemInfo.DELIVERY_AGENCY_ITEM_INFO.FEE_ITEM_NAME;
    }

    @Override
    public Field<String> field12() {
        return DeliveryAgencyItemInfo.DELIVERY_AGENCY_ITEM_INFO.INTERFACE_CODE;
    }

    @Override
    public Field<Integer> field13() {
        return DeliveryAgencyItemInfo.DELIVERY_AGENCY_ITEM_INFO.IS_DELETED;
    }

    @Override
    public Field<String> field14() {
        return DeliveryAgencyItemInfo.DELIVERY_AGENCY_ITEM_INFO.MODIFIED_BY;
    }

    @Override
    public Field<LocalDateTime> field15() {
        return DeliveryAgencyItemInfo.DELIVERY_AGENCY_ITEM_INFO.MODIFIED_DATE;
    }

    @Override
    public Field<String> field16() {
        return DeliveryAgencyItemInfo.DELIVERY_AGENCY_ITEM_INFO.NAME;
    }

    @Override
    public Field<String> field17() {
        return DeliveryAgencyItemInfo.DELIVERY_AGENCY_ITEM_INFO.OPERATION_METHOD;
    }

    @Override
    public Field<Integer> field18() {
        return DeliveryAgencyItemInfo.DELIVERY_AGENCY_ITEM_INFO.TYPE;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getAgencyId();
    }

    @Override
    public String component3() {
        return getCheckItemCode();
    }

    @Override
    public Long component4() {
        return getCheckItemId();
    }

    @Override
    public String component5() {
        return getCheckItemName();
    }

    @Override
    public String component6() {
        return getCode();
    }

    @Override
    public String component7() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime component8() {
        return getCreatedDate();
    }

    @Override
    public String component9() {
        return getFeeItemCode();
    }

    @Override
    public Long component10() {
        return getFeeItemId();
    }

    @Override
    public String component11() {
        return getFeeItemName();
    }

    @Override
    public String component12() {
        return getInterfaceCode();
    }

    @Override
    public Integer component13() {
        return getIsDeleted();
    }

    @Override
    public String component14() {
        return getModifiedBy();
    }

    @Override
    public LocalDateTime component15() {
        return getModifiedDate();
    }

    @Override
    public String component16() {
        return getName();
    }

    @Override
    public String component17() {
        return getOperationMethod();
    }

    @Override
    public Integer component18() {
        return getType();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getAgencyId();
    }

    @Override
    public String value3() {
        return getCheckItemCode();
    }

    @Override
    public Long value4() {
        return getCheckItemId();
    }

    @Override
    public String value5() {
        return getCheckItemName();
    }

    @Override
    public String value6() {
        return getCode();
    }

    @Override
    public String value7() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime value8() {
        return getCreatedDate();
    }

    @Override
    public String value9() {
        return getFeeItemCode();
    }

    @Override
    public Long value10() {
        return getFeeItemId();
    }

    @Override
    public String value11() {
        return getFeeItemName();
    }

    @Override
    public String value12() {
        return getInterfaceCode();
    }

    @Override
    public Integer value13() {
        return getIsDeleted();
    }

    @Override
    public String value14() {
        return getModifiedBy();
    }

    @Override
    public LocalDateTime value15() {
        return getModifiedDate();
    }

    @Override
    public String value16() {
        return getName();
    }

    @Override
    public String value17() {
        return getOperationMethod();
    }

    @Override
    public Integer value18() {
        return getType();
    }

    @Override
    public DeliveryAgencyItemInfoRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public DeliveryAgencyItemInfoRecord value2(Long value) {
        setAgencyId(value);
        return this;
    }

    @Override
    public DeliveryAgencyItemInfoRecord value3(String value) {
        setCheckItemCode(value);
        return this;
    }

    @Override
    public DeliveryAgencyItemInfoRecord value4(Long value) {
        setCheckItemId(value);
        return this;
    }

    @Override
    public DeliveryAgencyItemInfoRecord value5(String value) {
        setCheckItemName(value);
        return this;
    }

    @Override
    public DeliveryAgencyItemInfoRecord value6(String value) {
        setCode(value);
        return this;
    }

    @Override
    public DeliveryAgencyItemInfoRecord value7(String value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public DeliveryAgencyItemInfoRecord value8(LocalDateTime value) {
        setCreatedDate(value);
        return this;
    }

    @Override
    public DeliveryAgencyItemInfoRecord value9(String value) {
        setFeeItemCode(value);
        return this;
    }

    @Override
    public DeliveryAgencyItemInfoRecord value10(Long value) {
        setFeeItemId(value);
        return this;
    }

    @Override
    public DeliveryAgencyItemInfoRecord value11(String value) {
        setFeeItemName(value);
        return this;
    }

    @Override
    public DeliveryAgencyItemInfoRecord value12(String value) {
        setInterfaceCode(value);
        return this;
    }

    @Override
    public DeliveryAgencyItemInfoRecord value13(Integer value) {
        setIsDeleted(value);
        return this;
    }

    @Override
    public DeliveryAgencyItemInfoRecord value14(String value) {
        setModifiedBy(value);
        return this;
    }

    @Override
    public DeliveryAgencyItemInfoRecord value15(LocalDateTime value) {
        setModifiedDate(value);
        return this;
    }

    @Override
    public DeliveryAgencyItemInfoRecord value16(String value) {
        setName(value);
        return this;
    }

    @Override
    public DeliveryAgencyItemInfoRecord value17(String value) {
        setOperationMethod(value);
        return this;
    }

    @Override
    public DeliveryAgencyItemInfoRecord value18(Integer value) {
        setType(value);
        return this;
    }

    @Override
    public DeliveryAgencyItemInfoRecord values(Long value1, Long value2, String value3, Long value4, String value5, String value6, String value7, LocalDateTime value8, String value9, Long value10, String value11, String value12, Integer value13, String value14, LocalDateTime value15, String value16, String value17, Integer value18) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DeliveryAgencyItemInfoRecord
     */
    public DeliveryAgencyItemInfoRecord() {
        super(DeliveryAgencyItemInfo.DELIVERY_AGENCY_ITEM_INFO);
    }

    /**
     * Create a detached, initialised DeliveryAgencyItemInfoRecord
     */
    public DeliveryAgencyItemInfoRecord(Long id, Long agencyId, String checkItemCode, Long checkItemId, String checkItemName, String code, String createdBy, LocalDateTime createdDate, String feeItemCode, Long feeItemId, String feeItemName, String interfaceCode, Integer isDeleted, String modifiedBy, LocalDateTime modifiedDate, String name, String operationMethod, Integer type) {
        super(DeliveryAgencyItemInfo.DELIVERY_AGENCY_ITEM_INFO);

        setId(id);
        setAgencyId(agencyId);
        setCheckItemCode(checkItemCode);
        setCheckItemId(checkItemId);
        setCheckItemName(checkItemName);
        setCode(code);
        setCreatedBy(createdBy);
        setCreatedDate(createdDate);
        setFeeItemCode(feeItemCode);
        setFeeItemId(feeItemId);
        setFeeItemName(feeItemName);
        setInterfaceCode(interfaceCode);
        setIsDeleted(isDeleted);
        setModifiedBy(modifiedBy);
        setModifiedDate(modifiedDate);
        setName(name);
        setOperationMethod(operationMethod);
        setType(type);
    }
}
