/*
 * This file is generated by jOOQ.
 */
package com.example.boot.data.database.jooq.tables.records;


import com.example.boot.data.database.jooq.tables.PatientTempItemInfo;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PatientTempItemInfoRecord extends UpdatableRecordImpl<PatientTempItemInfoRecord> implements Record11<Long, String, LocalDateTime, Long, String, BigDecimal, Integer, String, LocalDateTime, String, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>physical_examination_system.patient_temp_item_info.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_temp_item_info.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>physical_examination_system.patient_temp_item_info.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_temp_item_info.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(1);
    }

    /**
     * Setter for <code>physical_examination_system.patient_temp_item_info.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_temp_item_info.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>physical_examination_system.patient_temp_item_info.fee_item_id</code>.
     */
    public void setFeeItemId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_temp_item_info.fee_item_id</code>.
     */
    public Long getFeeItemId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>physical_examination_system.patient_temp_item_info.fee_item_name</code>.
     */
    public void setFeeItemName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_temp_item_info.fee_item_name</code>.
     */
    public String getFeeItemName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>physical_examination_system.patient_temp_item_info.fee_item_price</code>.
     */
    public void setFeeItemPrice(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_temp_item_info.fee_item_price</code>.
     */
    public BigDecimal getFeeItemPrice() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>physical_examination_system.patient_temp_item_info.is_deleted</code>.
     */
    public void setIsDeleted(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_temp_item_info.is_deleted</code>.
     */
    public Integer getIsDeleted() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>physical_examination_system.patient_temp_item_info.modified_by</code>.
     */
    public void setModifiedBy(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_temp_item_info.modified_by</code>.
     */
    public String getModifiedBy() {
        return (String) get(7);
    }

    /**
     * Setter for <code>physical_examination_system.patient_temp_item_info.modified_date</code>.
     */
    public void setModifiedDate(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_temp_item_info.modified_date</code>.
     */
    public LocalDateTime getModifiedDate() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>physical_examination_system.patient_temp_item_info.patient_code</code>.
     */
    public void setPatientCode(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_temp_item_info.patient_code</code>.
     */
    public String getPatientCode() {
        return (String) get(9);
    }

    /**
     * Setter for <code>physical_examination_system.patient_temp_item_info.patient_id</code>.
     */
    public void setPatientId(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_temp_item_info.patient_id</code>.
     */
    public Long getPatientId() {
        return (Long) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<Long, String, LocalDateTime, Long, String, BigDecimal, Integer, String, LocalDateTime, String, Long> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<Long, String, LocalDateTime, Long, String, BigDecimal, Integer, String, LocalDateTime, String, Long> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return PatientTempItemInfo.PATIENT_TEMP_ITEM_INFO.ID;
    }

    @Override
    public Field<String> field2() {
        return PatientTempItemInfo.PATIENT_TEMP_ITEM_INFO.CREATED_BY;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return PatientTempItemInfo.PATIENT_TEMP_ITEM_INFO.CREATED_DATE;
    }

    @Override
    public Field<Long> field4() {
        return PatientTempItemInfo.PATIENT_TEMP_ITEM_INFO.FEE_ITEM_ID;
    }

    @Override
    public Field<String> field5() {
        return PatientTempItemInfo.PATIENT_TEMP_ITEM_INFO.FEE_ITEM_NAME;
    }

    @Override
    public Field<BigDecimal> field6() {
        return PatientTempItemInfo.PATIENT_TEMP_ITEM_INFO.FEE_ITEM_PRICE;
    }

    @Override
    public Field<Integer> field7() {
        return PatientTempItemInfo.PATIENT_TEMP_ITEM_INFO.IS_DELETED;
    }

    @Override
    public Field<String> field8() {
        return PatientTempItemInfo.PATIENT_TEMP_ITEM_INFO.MODIFIED_BY;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return PatientTempItemInfo.PATIENT_TEMP_ITEM_INFO.MODIFIED_DATE;
    }

    @Override
    public Field<String> field10() {
        return PatientTempItemInfo.PATIENT_TEMP_ITEM_INFO.PATIENT_CODE;
    }

    @Override
    public Field<Long> field11() {
        return PatientTempItemInfo.PATIENT_TEMP_ITEM_INFO.PATIENT_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime component3() {
        return getCreatedDate();
    }

    @Override
    public Long component4() {
        return getFeeItemId();
    }

    @Override
    public String component5() {
        return getFeeItemName();
    }

    @Override
    public BigDecimal component6() {
        return getFeeItemPrice();
    }

    @Override
    public Integer component7() {
        return getIsDeleted();
    }

    @Override
    public String component8() {
        return getModifiedBy();
    }

    @Override
    public LocalDateTime component9() {
        return getModifiedDate();
    }

    @Override
    public String component10() {
        return getPatientCode();
    }

    @Override
    public Long component11() {
        return getPatientId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime value3() {
        return getCreatedDate();
    }

    @Override
    public Long value4() {
        return getFeeItemId();
    }

    @Override
    public String value5() {
        return getFeeItemName();
    }

    @Override
    public BigDecimal value6() {
        return getFeeItemPrice();
    }

    @Override
    public Integer value7() {
        return getIsDeleted();
    }

    @Override
    public String value8() {
        return getModifiedBy();
    }

    @Override
    public LocalDateTime value9() {
        return getModifiedDate();
    }

    @Override
    public String value10() {
        return getPatientCode();
    }

    @Override
    public Long value11() {
        return getPatientId();
    }

    @Override
    public PatientTempItemInfoRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public PatientTempItemInfoRecord value2(String value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public PatientTempItemInfoRecord value3(LocalDateTime value) {
        setCreatedDate(value);
        return this;
    }

    @Override
    public PatientTempItemInfoRecord value4(Long value) {
        setFeeItemId(value);
        return this;
    }

    @Override
    public PatientTempItemInfoRecord value5(String value) {
        setFeeItemName(value);
        return this;
    }

    @Override
    public PatientTempItemInfoRecord value6(BigDecimal value) {
        setFeeItemPrice(value);
        return this;
    }

    @Override
    public PatientTempItemInfoRecord value7(Integer value) {
        setIsDeleted(value);
        return this;
    }

    @Override
    public PatientTempItemInfoRecord value8(String value) {
        setModifiedBy(value);
        return this;
    }

    @Override
    public PatientTempItemInfoRecord value9(LocalDateTime value) {
        setModifiedDate(value);
        return this;
    }

    @Override
    public PatientTempItemInfoRecord value10(String value) {
        setPatientCode(value);
        return this;
    }

    @Override
    public PatientTempItemInfoRecord value11(Long value) {
        setPatientId(value);
        return this;
    }

    @Override
    public PatientTempItemInfoRecord values(Long value1, String value2, LocalDateTime value3, Long value4, String value5, BigDecimal value6, Integer value7, String value8, LocalDateTime value9, String value10, Long value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PatientTempItemInfoRecord
     */
    public PatientTempItemInfoRecord() {
        super(PatientTempItemInfo.PATIENT_TEMP_ITEM_INFO);
    }

    /**
     * Create a detached, initialised PatientTempItemInfoRecord
     */
    public PatientTempItemInfoRecord(Long id, String createdBy, LocalDateTime createdDate, Long feeItemId, String feeItemName, BigDecimal feeItemPrice, Integer isDeleted, String modifiedBy, LocalDateTime modifiedDate, String patientCode, Long patientId) {
        super(PatientTempItemInfo.PATIENT_TEMP_ITEM_INFO);

        setId(id);
        setCreatedBy(createdBy);
        setCreatedDate(createdDate);
        setFeeItemId(feeItemId);
        setFeeItemName(feeItemName);
        setFeeItemPrice(feeItemPrice);
        setIsDeleted(isDeleted);
        setModifiedBy(modifiedBy);
        setModifiedDate(modifiedDate);
        setPatientCode(patientCode);
        setPatientId(patientId);
    }
}
