/*
 * This file is generated by jOOQ.
 */
package com.example.boot.data.database.jooq.tables.records;


import com.example.boot.data.database.jooq.tables.PatientExamInfo;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record19;
import org.jooq.Row19;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PatientExamInfoRecord extends UpdatableRecordImpl<PatientExamInfoRecord> implements Record19<Long, Integer, LocalDateTime, LocalDateTime, Integer, String, LocalDateTime, Integer, String, Integer, LocalDateTime, String, LocalDateTime, String, String, String, LocalDateTime, Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>physical_examination_system.patient_exam_info.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_exam_info.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>physical_examination_system.patient_exam_info.age</code>.
     */
    public void setAge(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_exam_info.age</code>.
     */
    public Integer getAge() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>physical_examination_system.patient_exam_info.check_completion_time</code>.
     */
    public void setCheckCompletionTime(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_exam_info.check_completion_time</code>.
     */
    public LocalDateTime getCheckCompletionTime() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>physical_examination_system.patient_exam_info.check_outage_time</code>.
     */
    public void setCheckOutageTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_exam_info.check_outage_time</code>.
     */
    public LocalDateTime getCheckOutageTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>physical_examination_system.patient_exam_info.check_status</code>.
     */
    public void setCheckStatus(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_exam_info.check_status</code>.
     */
    public Integer getCheckStatus() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>physical_examination_system.patient_exam_info.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_exam_info.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(5);
    }

    /**
     * Setter for <code>physical_examination_system.patient_exam_info.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_exam_info.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>physical_examination_system.patient_exam_info.gender</code>.
     */
    public void setGender(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_exam_info.gender</code>.
     */
    public Integer getGender() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>physical_examination_system.patient_exam_info.id_card_no</code>.
     */
    public void setIdCardNo(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_exam_info.id_card_no</code>.
     */
    public String getIdCardNo() {
        return (String) get(8);
    }

    /**
     * Setter for <code>physical_examination_system.patient_exam_info.is_deleted</code>.
     */
    public void setIsDeleted(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_exam_info.is_deleted</code>.
     */
    public Integer getIsDeleted() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>physical_examination_system.patient_exam_info.is_register</code>.
     */
    public void setIsRegister(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_exam_info.is_register</code>.
     */
    public LocalDateTime getIsRegister() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>physical_examination_system.patient_exam_info.modified_by</code>.
     */
    public void setModifiedBy(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_exam_info.modified_by</code>.
     */
    public String getModifiedBy() {
        return (String) get(11);
    }

    /**
     * Setter for <code>physical_examination_system.patient_exam_info.modified_date</code>.
     */
    public void setModifiedDate(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_exam_info.modified_date</code>.
     */
    public LocalDateTime getModifiedDate() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>physical_examination_system.patient_exam_info.name</code>.
     */
    public void setName(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_exam_info.name</code>.
     */
    public String getName() {
        return (String) get(13);
    }

    /**
     * Setter for <code>physical_examination_system.patient_exam_info.password</code>.
     */
    public void setPassword(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_exam_info.password</code>.
     */
    public String getPassword() {
        return (String) get(14);
    }

    /**
     * Setter for <code>physical_examination_system.patient_exam_info.phone</code>.
     */
    public void setPhone(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_exam_info.phone</code>.
     */
    public String getPhone() {
        return (String) get(15);
    }

    /**
     * Setter for <code>physical_examination_system.patient_exam_info.register_time</code>.
     */
    public void setRegisterTime(LocalDateTime value) {
        set(16, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_exam_info.register_time</code>.
     */
    public LocalDateTime getRegisterTime() {
        return (LocalDateTime) get(16);
    }

    /**
     * Setter for <code>physical_examination_system.patient_exam_info.report_status</code>.
     */
    public void setReportStatus(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_exam_info.report_status</code>.
     */
    public Integer getReportStatus() {
        return (Integer) get(17);
    }

    /**
     * Setter for <code>physical_examination_system.patient_exam_info.username</code>.
     */
    public void setUsername(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_exam_info.username</code>.
     */
    public String getUsername() {
        return (String) get(18);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record19 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row19<Long, Integer, LocalDateTime, LocalDateTime, Integer, String, LocalDateTime, Integer, String, Integer, LocalDateTime, String, LocalDateTime, String, String, String, LocalDateTime, Integer, String> fieldsRow() {
        return (Row19) super.fieldsRow();
    }

    @Override
    public Row19<Long, Integer, LocalDateTime, LocalDateTime, Integer, String, LocalDateTime, Integer, String, Integer, LocalDateTime, String, LocalDateTime, String, String, String, LocalDateTime, Integer, String> valuesRow() {
        return (Row19) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return PatientExamInfo.PATIENT_EXAM_INFO.ID;
    }

    @Override
    public Field<Integer> field2() {
        return PatientExamInfo.PATIENT_EXAM_INFO.AGE;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return PatientExamInfo.PATIENT_EXAM_INFO.CHECK_COMPLETION_TIME;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return PatientExamInfo.PATIENT_EXAM_INFO.CHECK_OUTAGE_TIME;
    }

    @Override
    public Field<Integer> field5() {
        return PatientExamInfo.PATIENT_EXAM_INFO.CHECK_STATUS;
    }

    @Override
    public Field<String> field6() {
        return PatientExamInfo.PATIENT_EXAM_INFO.CREATED_BY;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return PatientExamInfo.PATIENT_EXAM_INFO.CREATED_DATE;
    }

    @Override
    public Field<Integer> field8() {
        return PatientExamInfo.PATIENT_EXAM_INFO.GENDER;
    }

    @Override
    public Field<String> field9() {
        return PatientExamInfo.PATIENT_EXAM_INFO.ID_CARD_NO;
    }

    @Override
    public Field<Integer> field10() {
        return PatientExamInfo.PATIENT_EXAM_INFO.IS_DELETED;
    }

    @Override
    public Field<LocalDateTime> field11() {
        return PatientExamInfo.PATIENT_EXAM_INFO.IS_REGISTER;
    }

    @Override
    public Field<String> field12() {
        return PatientExamInfo.PATIENT_EXAM_INFO.MODIFIED_BY;
    }

    @Override
    public Field<LocalDateTime> field13() {
        return PatientExamInfo.PATIENT_EXAM_INFO.MODIFIED_DATE;
    }

    @Override
    public Field<String> field14() {
        return PatientExamInfo.PATIENT_EXAM_INFO.NAME;
    }

    @Override
    public Field<String> field15() {
        return PatientExamInfo.PATIENT_EXAM_INFO.PASSWORD;
    }

    @Override
    public Field<String> field16() {
        return PatientExamInfo.PATIENT_EXAM_INFO.PHONE;
    }

    @Override
    public Field<LocalDateTime> field17() {
        return PatientExamInfo.PATIENT_EXAM_INFO.REGISTER_TIME;
    }

    @Override
    public Field<Integer> field18() {
        return PatientExamInfo.PATIENT_EXAM_INFO.REPORT_STATUS;
    }

    @Override
    public Field<String> field19() {
        return PatientExamInfo.PATIENT_EXAM_INFO.USERNAME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getAge();
    }

    @Override
    public LocalDateTime component3() {
        return getCheckCompletionTime();
    }

    @Override
    public LocalDateTime component4() {
        return getCheckOutageTime();
    }

    @Override
    public Integer component5() {
        return getCheckStatus();
    }

    @Override
    public String component6() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime component7() {
        return getCreatedDate();
    }

    @Override
    public Integer component8() {
        return getGender();
    }

    @Override
    public String component9() {
        return getIdCardNo();
    }

    @Override
    public Integer component10() {
        return getIsDeleted();
    }

    @Override
    public LocalDateTime component11() {
        return getIsRegister();
    }

    @Override
    public String component12() {
        return getModifiedBy();
    }

    @Override
    public LocalDateTime component13() {
        return getModifiedDate();
    }

    @Override
    public String component14() {
        return getName();
    }

    @Override
    public String component15() {
        return getPassword();
    }

    @Override
    public String component16() {
        return getPhone();
    }

    @Override
    public LocalDateTime component17() {
        return getRegisterTime();
    }

    @Override
    public Integer component18() {
        return getReportStatus();
    }

    @Override
    public String component19() {
        return getUsername();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getAge();
    }

    @Override
    public LocalDateTime value3() {
        return getCheckCompletionTime();
    }

    @Override
    public LocalDateTime value4() {
        return getCheckOutageTime();
    }

    @Override
    public Integer value5() {
        return getCheckStatus();
    }

    @Override
    public String value6() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime value7() {
        return getCreatedDate();
    }

    @Override
    public Integer value8() {
        return getGender();
    }

    @Override
    public String value9() {
        return getIdCardNo();
    }

    @Override
    public Integer value10() {
        return getIsDeleted();
    }

    @Override
    public LocalDateTime value11() {
        return getIsRegister();
    }

    @Override
    public String value12() {
        return getModifiedBy();
    }

    @Override
    public LocalDateTime value13() {
        return getModifiedDate();
    }

    @Override
    public String value14() {
        return getName();
    }

    @Override
    public String value15() {
        return getPassword();
    }

    @Override
    public String value16() {
        return getPhone();
    }

    @Override
    public LocalDateTime value17() {
        return getRegisterTime();
    }

    @Override
    public Integer value18() {
        return getReportStatus();
    }

    @Override
    public String value19() {
        return getUsername();
    }

    @Override
    public PatientExamInfoRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public PatientExamInfoRecord value2(Integer value) {
        setAge(value);
        return this;
    }

    @Override
    public PatientExamInfoRecord value3(LocalDateTime value) {
        setCheckCompletionTime(value);
        return this;
    }

    @Override
    public PatientExamInfoRecord value4(LocalDateTime value) {
        setCheckOutageTime(value);
        return this;
    }

    @Override
    public PatientExamInfoRecord value5(Integer value) {
        setCheckStatus(value);
        return this;
    }

    @Override
    public PatientExamInfoRecord value6(String value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public PatientExamInfoRecord value7(LocalDateTime value) {
        setCreatedDate(value);
        return this;
    }

    @Override
    public PatientExamInfoRecord value8(Integer value) {
        setGender(value);
        return this;
    }

    @Override
    public PatientExamInfoRecord value9(String value) {
        setIdCardNo(value);
        return this;
    }

    @Override
    public PatientExamInfoRecord value10(Integer value) {
        setIsDeleted(value);
        return this;
    }

    @Override
    public PatientExamInfoRecord value11(LocalDateTime value) {
        setIsRegister(value);
        return this;
    }

    @Override
    public PatientExamInfoRecord value12(String value) {
        setModifiedBy(value);
        return this;
    }

    @Override
    public PatientExamInfoRecord value13(LocalDateTime value) {
        setModifiedDate(value);
        return this;
    }

    @Override
    public PatientExamInfoRecord value14(String value) {
        setName(value);
        return this;
    }

    @Override
    public PatientExamInfoRecord value15(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public PatientExamInfoRecord value16(String value) {
        setPhone(value);
        return this;
    }

    @Override
    public PatientExamInfoRecord value17(LocalDateTime value) {
        setRegisterTime(value);
        return this;
    }

    @Override
    public PatientExamInfoRecord value18(Integer value) {
        setReportStatus(value);
        return this;
    }

    @Override
    public PatientExamInfoRecord value19(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public PatientExamInfoRecord values(Long value1, Integer value2, LocalDateTime value3, LocalDateTime value4, Integer value5, String value6, LocalDateTime value7, Integer value8, String value9, Integer value10, LocalDateTime value11, String value12, LocalDateTime value13, String value14, String value15, String value16, LocalDateTime value17, Integer value18, String value19) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PatientExamInfoRecord
     */
    public PatientExamInfoRecord() {
        super(PatientExamInfo.PATIENT_EXAM_INFO);
    }

    /**
     * Create a detached, initialised PatientExamInfoRecord
     */
    public PatientExamInfoRecord(Long id, Integer age, LocalDateTime checkCompletionTime, LocalDateTime checkOutageTime, Integer checkStatus, String createdBy, LocalDateTime createdDate, Integer gender, String idCardNo, Integer isDeleted, LocalDateTime isRegister, String modifiedBy, LocalDateTime modifiedDate, String name, String password, String phone, LocalDateTime registerTime, Integer reportStatus, String username) {
        super(PatientExamInfo.PATIENT_EXAM_INFO);

        setId(id);
        setAge(age);
        setCheckCompletionTime(checkCompletionTime);
        setCheckOutageTime(checkOutageTime);
        setCheckStatus(checkStatus);
        setCreatedBy(createdBy);
        setCreatedDate(createdDate);
        setGender(gender);
        setIdCardNo(idCardNo);
        setIsDeleted(isDeleted);
        setIsRegister(isRegister);
        setModifiedBy(modifiedBy);
        setModifiedDate(modifiedDate);
        setName(name);
        setPassword(password);
        setPhone(phone);
        setRegisterTime(registerTime);
        setReportStatus(reportStatus);
        setUsername(username);
    }
}
