/*
 * This file is generated by jOOQ.
 */
package com.example.boot.data.database.jooq.tables.records;


import com.example.boot.data.database.jooq.tables.PatientMealInfo;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PatientMealInfoRecord extends UpdatableRecordImpl<PatientMealInfoRecord> implements Record10<Long, String, LocalDateTime, Integer, Long, String, String, LocalDateTime, String, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>physical_examination_system.patient_meal_info.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_meal_info.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>physical_examination_system.patient_meal_info.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_meal_info.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(1);
    }

    /**
     * Setter for <code>physical_examination_system.patient_meal_info.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_meal_info.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>physical_examination_system.patient_meal_info.is_deleted</code>.
     */
    public void setIsDeleted(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_meal_info.is_deleted</code>.
     */
    public Integer getIsDeleted() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>physical_examination_system.patient_meal_info.meal_id</code>.
     */
    public void setMealId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_meal_info.meal_id</code>.
     */
    public Long getMealId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>physical_examination_system.patient_meal_info.meal_name</code>.
     */
    public void setMealName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_meal_info.meal_name</code>.
     */
    public String getMealName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>physical_examination_system.patient_meal_info.modified_by</code>.
     */
    public void setModifiedBy(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_meal_info.modified_by</code>.
     */
    public String getModifiedBy() {
        return (String) get(6);
    }

    /**
     * Setter for <code>physical_examination_system.patient_meal_info.modified_date</code>.
     */
    public void setModifiedDate(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_meal_info.modified_date</code>.
     */
    public LocalDateTime getModifiedDate() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>physical_examination_system.patient_meal_info.patient_code</code>.
     */
    public void setPatientCode(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_meal_info.patient_code</code>.
     */
    public String getPatientCode() {
        return (String) get(8);
    }

    /**
     * Setter for <code>physical_examination_system.patient_meal_info.patient_id</code>.
     */
    public void setPatientId(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_meal_info.patient_id</code>.
     */
    public Long getPatientId() {
        return (Long) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, String, LocalDateTime, Integer, Long, String, String, LocalDateTime, String, Long> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Long, String, LocalDateTime, Integer, Long, String, String, LocalDateTime, String, Long> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return PatientMealInfo.PATIENT_MEAL_INFO.ID;
    }

    @Override
    public Field<String> field2() {
        return PatientMealInfo.PATIENT_MEAL_INFO.CREATED_BY;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return PatientMealInfo.PATIENT_MEAL_INFO.CREATED_DATE;
    }

    @Override
    public Field<Integer> field4() {
        return PatientMealInfo.PATIENT_MEAL_INFO.IS_DELETED;
    }

    @Override
    public Field<Long> field5() {
        return PatientMealInfo.PATIENT_MEAL_INFO.MEAL_ID;
    }

    @Override
    public Field<String> field6() {
        return PatientMealInfo.PATIENT_MEAL_INFO.MEAL_NAME;
    }

    @Override
    public Field<String> field7() {
        return PatientMealInfo.PATIENT_MEAL_INFO.MODIFIED_BY;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return PatientMealInfo.PATIENT_MEAL_INFO.MODIFIED_DATE;
    }

    @Override
    public Field<String> field9() {
        return PatientMealInfo.PATIENT_MEAL_INFO.PATIENT_CODE;
    }

    @Override
    public Field<Long> field10() {
        return PatientMealInfo.PATIENT_MEAL_INFO.PATIENT_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime component3() {
        return getCreatedDate();
    }

    @Override
    public Integer component4() {
        return getIsDeleted();
    }

    @Override
    public Long component5() {
        return getMealId();
    }

    @Override
    public String component6() {
        return getMealName();
    }

    @Override
    public String component7() {
        return getModifiedBy();
    }

    @Override
    public LocalDateTime component8() {
        return getModifiedDate();
    }

    @Override
    public String component9() {
        return getPatientCode();
    }

    @Override
    public Long component10() {
        return getPatientId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime value3() {
        return getCreatedDate();
    }

    @Override
    public Integer value4() {
        return getIsDeleted();
    }

    @Override
    public Long value5() {
        return getMealId();
    }

    @Override
    public String value6() {
        return getMealName();
    }

    @Override
    public String value7() {
        return getModifiedBy();
    }

    @Override
    public LocalDateTime value8() {
        return getModifiedDate();
    }

    @Override
    public String value9() {
        return getPatientCode();
    }

    @Override
    public Long value10() {
        return getPatientId();
    }

    @Override
    public PatientMealInfoRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public PatientMealInfoRecord value2(String value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public PatientMealInfoRecord value3(LocalDateTime value) {
        setCreatedDate(value);
        return this;
    }

    @Override
    public PatientMealInfoRecord value4(Integer value) {
        setIsDeleted(value);
        return this;
    }

    @Override
    public PatientMealInfoRecord value5(Long value) {
        setMealId(value);
        return this;
    }

    @Override
    public PatientMealInfoRecord value6(String value) {
        setMealName(value);
        return this;
    }

    @Override
    public PatientMealInfoRecord value7(String value) {
        setModifiedBy(value);
        return this;
    }

    @Override
    public PatientMealInfoRecord value8(LocalDateTime value) {
        setModifiedDate(value);
        return this;
    }

    @Override
    public PatientMealInfoRecord value9(String value) {
        setPatientCode(value);
        return this;
    }

    @Override
    public PatientMealInfoRecord value10(Long value) {
        setPatientId(value);
        return this;
    }

    @Override
    public PatientMealInfoRecord values(Long value1, String value2, LocalDateTime value3, Integer value4, Long value5, String value6, String value7, LocalDateTime value8, String value9, Long value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PatientMealInfoRecord
     */
    public PatientMealInfoRecord() {
        super(PatientMealInfo.PATIENT_MEAL_INFO);
    }

    /**
     * Create a detached, initialised PatientMealInfoRecord
     */
    public PatientMealInfoRecord(Long id, String createdBy, LocalDateTime createdDate, Integer isDeleted, Long mealId, String mealName, String modifiedBy, LocalDateTime modifiedDate, String patientCode, Long patientId) {
        super(PatientMealInfo.PATIENT_MEAL_INFO);

        setId(id);
        setCreatedBy(createdBy);
        setCreatedDate(createdDate);
        setIsDeleted(isDeleted);
        setMealId(mealId);
        setMealName(mealName);
        setModifiedBy(modifiedBy);
        setModifiedDate(modifiedDate);
        setPatientCode(patientCode);
        setPatientId(patientId);
    }
}
