/*
 * This file is generated by jOOQ.
 */
package com.example.boot.data.database.jooq.tables.records;


import com.example.boot.data.database.jooq.tables.PatientTotalConclusionInfo;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PatientTotalConclusionInfoRecord extends UpdatableRecordImpl<PatientTotalConclusionInfoRecord> implements Record10<Long, String, String, LocalDateTime, Integer, Integer, String, LocalDateTime, String, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>physical_examination_system.patient_total_conclusion_info.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_total_conclusion_info.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>physical_examination_system.patient_total_conclusion_info.conclusion</code>.
     */
    public void setConclusion(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_total_conclusion_info.conclusion</code>.
     */
    public String getConclusion() {
        return (String) get(1);
    }

    /**
     * Setter for <code>physical_examination_system.patient_total_conclusion_info.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_total_conclusion_info.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(2);
    }

    /**
     * Setter for <code>physical_examination_system.patient_total_conclusion_info.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_total_conclusion_info.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>physical_examination_system.patient_total_conclusion_info.is_abnormal</code>.
     */
    public void setIsAbnormal(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_total_conclusion_info.is_abnormal</code>.
     */
    public Integer getIsAbnormal() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>physical_examination_system.patient_total_conclusion_info.is_deleted</code>.
     */
    public void setIsDeleted(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_total_conclusion_info.is_deleted</code>.
     */
    public Integer getIsDeleted() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>physical_examination_system.patient_total_conclusion_info.modified_by</code>.
     */
    public void setModifiedBy(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_total_conclusion_info.modified_by</code>.
     */
    public String getModifiedBy() {
        return (String) get(6);
    }

    /**
     * Setter for <code>physical_examination_system.patient_total_conclusion_info.modified_date</code>.
     */
    public void setModifiedDate(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_total_conclusion_info.modified_date</code>.
     */
    public LocalDateTime getModifiedDate() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>physical_examination_system.patient_total_conclusion_info.patient_code</code>.
     */
    public void setPatientCode(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_total_conclusion_info.patient_code</code>.
     */
    public String getPatientCode() {
        return (String) get(8);
    }

    /**
     * Setter for <code>physical_examination_system.patient_total_conclusion_info.patient_id</code>.
     */
    public void setPatientId(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>physical_examination_system.patient_total_conclusion_info.patient_id</code>.
     */
    public Long getPatientId() {
        return (Long) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, String, String, LocalDateTime, Integer, Integer, String, LocalDateTime, String, Long> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Long, String, String, LocalDateTime, Integer, Integer, String, LocalDateTime, String, Long> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return PatientTotalConclusionInfo.PATIENT_TOTAL_CONCLUSION_INFO.ID;
    }

    @Override
    public Field<String> field2() {
        return PatientTotalConclusionInfo.PATIENT_TOTAL_CONCLUSION_INFO.CONCLUSION;
    }

    @Override
    public Field<String> field3() {
        return PatientTotalConclusionInfo.PATIENT_TOTAL_CONCLUSION_INFO.CREATED_BY;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return PatientTotalConclusionInfo.PATIENT_TOTAL_CONCLUSION_INFO.CREATED_DATE;
    }

    @Override
    public Field<Integer> field5() {
        return PatientTotalConclusionInfo.PATIENT_TOTAL_CONCLUSION_INFO.IS_ABNORMAL;
    }

    @Override
    public Field<Integer> field6() {
        return PatientTotalConclusionInfo.PATIENT_TOTAL_CONCLUSION_INFO.IS_DELETED;
    }

    @Override
    public Field<String> field7() {
        return PatientTotalConclusionInfo.PATIENT_TOTAL_CONCLUSION_INFO.MODIFIED_BY;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return PatientTotalConclusionInfo.PATIENT_TOTAL_CONCLUSION_INFO.MODIFIED_DATE;
    }

    @Override
    public Field<String> field9() {
        return PatientTotalConclusionInfo.PATIENT_TOTAL_CONCLUSION_INFO.PATIENT_CODE;
    }

    @Override
    public Field<Long> field10() {
        return PatientTotalConclusionInfo.PATIENT_TOTAL_CONCLUSION_INFO.PATIENT_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getConclusion();
    }

    @Override
    public String component3() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime component4() {
        return getCreatedDate();
    }

    @Override
    public Integer component5() {
        return getIsAbnormal();
    }

    @Override
    public Integer component6() {
        return getIsDeleted();
    }

    @Override
    public String component7() {
        return getModifiedBy();
    }

    @Override
    public LocalDateTime component8() {
        return getModifiedDate();
    }

    @Override
    public String component9() {
        return getPatientCode();
    }

    @Override
    public Long component10() {
        return getPatientId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getConclusion();
    }

    @Override
    public String value3() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime value4() {
        return getCreatedDate();
    }

    @Override
    public Integer value5() {
        return getIsAbnormal();
    }

    @Override
    public Integer value6() {
        return getIsDeleted();
    }

    @Override
    public String value7() {
        return getModifiedBy();
    }

    @Override
    public LocalDateTime value8() {
        return getModifiedDate();
    }

    @Override
    public String value9() {
        return getPatientCode();
    }

    @Override
    public Long value10() {
        return getPatientId();
    }

    @Override
    public PatientTotalConclusionInfoRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public PatientTotalConclusionInfoRecord value2(String value) {
        setConclusion(value);
        return this;
    }

    @Override
    public PatientTotalConclusionInfoRecord value3(String value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public PatientTotalConclusionInfoRecord value4(LocalDateTime value) {
        setCreatedDate(value);
        return this;
    }

    @Override
    public PatientTotalConclusionInfoRecord value5(Integer value) {
        setIsAbnormal(value);
        return this;
    }

    @Override
    public PatientTotalConclusionInfoRecord value6(Integer value) {
        setIsDeleted(value);
        return this;
    }

    @Override
    public PatientTotalConclusionInfoRecord value7(String value) {
        setModifiedBy(value);
        return this;
    }

    @Override
    public PatientTotalConclusionInfoRecord value8(LocalDateTime value) {
        setModifiedDate(value);
        return this;
    }

    @Override
    public PatientTotalConclusionInfoRecord value9(String value) {
        setPatientCode(value);
        return this;
    }

    @Override
    public PatientTotalConclusionInfoRecord value10(Long value) {
        setPatientId(value);
        return this;
    }

    @Override
    public PatientTotalConclusionInfoRecord values(Long value1, String value2, String value3, LocalDateTime value4, Integer value5, Integer value6, String value7, LocalDateTime value8, String value9, Long value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PatientTotalConclusionInfoRecord
     */
    public PatientTotalConclusionInfoRecord() {
        super(PatientTotalConclusionInfo.PATIENT_TOTAL_CONCLUSION_INFO);
    }

    /**
     * Create a detached, initialised PatientTotalConclusionInfoRecord
     */
    public PatientTotalConclusionInfoRecord(Long id, String conclusion, String createdBy, LocalDateTime createdDate, Integer isAbnormal, Integer isDeleted, String modifiedBy, LocalDateTime modifiedDate, String patientCode, Long patientId) {
        super(PatientTotalConclusionInfo.PATIENT_TOTAL_CONCLUSION_INFO);

        setId(id);
        setConclusion(conclusion);
        setCreatedBy(createdBy);
        setCreatedDate(createdDate);
        setIsAbnormal(isAbnormal);
        setIsDeleted(isDeleted);
        setModifiedBy(modifiedBy);
        setModifiedDate(modifiedDate);
        setPatientCode(patientCode);
        setPatientId(patientId);
    }
}
