/*
 * This file is generated by jOOQ.
 */
package com.example.boot.data.database.jooq.tables.records;


import com.example.boot.data.database.jooq.tables.SystemPermissionInfo;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * system_permission_info
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SystemPermissionInfoRecord extends UpdatableRecordImpl<SystemPermissionInfoRecord> implements Record11<Long, LocalDateTime, LocalDateTime, String, String, Integer, String, String, String, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>physical_examination_system.system_permission_info.id</code>. id
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>physical_examination_system.system_permission_info.id</code>. id
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>physical_examination_system.system_permission_info.created_date</code>. createdDate
     */
    public void setCreatedDate(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>physical_examination_system.system_permission_info.created_date</code>. createdDate
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>physical_examination_system.system_permission_info.modified_date</code>. modifiedDate
     */
    public void setModifiedDate(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>physical_examination_system.system_permission_info.modified_date</code>. modifiedDate
     */
    public LocalDateTime getModifiedDate() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>physical_examination_system.system_permission_info.created_by</code>. createdBy
     */
    public void setCreatedBy(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>physical_examination_system.system_permission_info.created_by</code>. createdBy
     */
    public String getCreatedBy() {
        return (String) get(3);
    }

    /**
     * Setter for <code>physical_examination_system.system_permission_info.modified_by</code>. modifiedBy
     */
    public void setModifiedBy(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>physical_examination_system.system_permission_info.modified_by</code>. modifiedBy
     */
    public String getModifiedBy() {
        return (String) get(4);
    }

    /**
     * Setter for <code>physical_examination_system.system_permission_info.is_deleted</code>. isDeleted
     */
    public void setIsDeleted(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>physical_examination_system.system_permission_info.is_deleted</code>. isDeleted
     */
    public Integer getIsDeleted() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>physical_examination_system.system_permission_info.name</code>. 权限名称
     */
    public void setName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>physical_examination_system.system_permission_info.name</code>. 权限名称
     */
    public String getName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>physical_examination_system.system_permission_info.module</code>. 模块名称
     */
    public void setModule(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>physical_examination_system.system_permission_info.module</code>. 模块名称
     */
    public String getModule() {
        return (String) get(7);
    }

    /**
     * Setter for <code>physical_examination_system.system_permission_info.full_name</code>. 全名称
     * 模块名称:权限名称
     */
    public void setFullName(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>physical_examination_system.system_permission_info.full_name</code>. 全名称
     * 模块名称:权限名称
     */
    public String getFullName() {
        return (String) get(8);
    }

    /**
     * Setter for <code>physical_examination_system.system_permission_info.level</code>. 排序
     */
    public void setLevel(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>physical_examination_system.system_permission_info.level</code>. 排序
     */
    public Integer getLevel() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>physical_examination_system.system_permission_info.is_enabled</code>. 是否启用
     * 0 否 1 是
     */
    public void setIsEnabled(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>physical_examination_system.system_permission_info.is_enabled</code>. 是否启用
     * 0 否 1 是
     */
    public Integer getIsEnabled() {
        return (Integer) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<Long, LocalDateTime, LocalDateTime, String, String, Integer, String, String, String, Integer, Integer> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<Long, LocalDateTime, LocalDateTime, String, String, Integer, String, String, String, Integer, Integer> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return SystemPermissionInfo.SYSTEM_PERMISSION_INFO.ID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return SystemPermissionInfo.SYSTEM_PERMISSION_INFO.CREATED_DATE;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return SystemPermissionInfo.SYSTEM_PERMISSION_INFO.MODIFIED_DATE;
    }

    @Override
    public Field<String> field4() {
        return SystemPermissionInfo.SYSTEM_PERMISSION_INFO.CREATED_BY;
    }

    @Override
    public Field<String> field5() {
        return SystemPermissionInfo.SYSTEM_PERMISSION_INFO.MODIFIED_BY;
    }

    @Override
    public Field<Integer> field6() {
        return SystemPermissionInfo.SYSTEM_PERMISSION_INFO.IS_DELETED;
    }

    @Override
    public Field<String> field7() {
        return SystemPermissionInfo.SYSTEM_PERMISSION_INFO.NAME;
    }

    @Override
    public Field<String> field8() {
        return SystemPermissionInfo.SYSTEM_PERMISSION_INFO.MODULE;
    }

    @Override
    public Field<String> field9() {
        return SystemPermissionInfo.SYSTEM_PERMISSION_INFO.FULL_NAME;
    }

    @Override
    public Field<Integer> field10() {
        return SystemPermissionInfo.SYSTEM_PERMISSION_INFO.LEVEL;
    }

    @Override
    public Field<Integer> field11() {
        return SystemPermissionInfo.SYSTEM_PERMISSION_INFO.IS_ENABLED;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public LocalDateTime component2() {
        return getCreatedDate();
    }

    @Override
    public LocalDateTime component3() {
        return getModifiedDate();
    }

    @Override
    public String component4() {
        return getCreatedBy();
    }

    @Override
    public String component5() {
        return getModifiedBy();
    }

    @Override
    public Integer component6() {
        return getIsDeleted();
    }

    @Override
    public String component7() {
        return getName();
    }

    @Override
    public String component8() {
        return getModule();
    }

    @Override
    public String component9() {
        return getFullName();
    }

    @Override
    public Integer component10() {
        return getLevel();
    }

    @Override
    public Integer component11() {
        return getIsEnabled();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public LocalDateTime value2() {
        return getCreatedDate();
    }

    @Override
    public LocalDateTime value3() {
        return getModifiedDate();
    }

    @Override
    public String value4() {
        return getCreatedBy();
    }

    @Override
    public String value5() {
        return getModifiedBy();
    }

    @Override
    public Integer value6() {
        return getIsDeleted();
    }

    @Override
    public String value7() {
        return getName();
    }

    @Override
    public String value8() {
        return getModule();
    }

    @Override
    public String value9() {
        return getFullName();
    }

    @Override
    public Integer value10() {
        return getLevel();
    }

    @Override
    public Integer value11() {
        return getIsEnabled();
    }

    @Override
    public SystemPermissionInfoRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public SystemPermissionInfoRecord value2(LocalDateTime value) {
        setCreatedDate(value);
        return this;
    }

    @Override
    public SystemPermissionInfoRecord value3(LocalDateTime value) {
        setModifiedDate(value);
        return this;
    }

    @Override
    public SystemPermissionInfoRecord value4(String value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public SystemPermissionInfoRecord value5(String value) {
        setModifiedBy(value);
        return this;
    }

    @Override
    public SystemPermissionInfoRecord value6(Integer value) {
        setIsDeleted(value);
        return this;
    }

    @Override
    public SystemPermissionInfoRecord value7(String value) {
        setName(value);
        return this;
    }

    @Override
    public SystemPermissionInfoRecord value8(String value) {
        setModule(value);
        return this;
    }

    @Override
    public SystemPermissionInfoRecord value9(String value) {
        setFullName(value);
        return this;
    }

    @Override
    public SystemPermissionInfoRecord value10(Integer value) {
        setLevel(value);
        return this;
    }

    @Override
    public SystemPermissionInfoRecord value11(Integer value) {
        setIsEnabled(value);
        return this;
    }

    @Override
    public SystemPermissionInfoRecord values(Long value1, LocalDateTime value2, LocalDateTime value3, String value4, String value5, Integer value6, String value7, String value8, String value9, Integer value10, Integer value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SystemPermissionInfoRecord
     */
    public SystemPermissionInfoRecord() {
        super(SystemPermissionInfo.SYSTEM_PERMISSION_INFO);
    }

    /**
     * Create a detached, initialised SystemPermissionInfoRecord
     */
    public SystemPermissionInfoRecord(Long id, LocalDateTime createdDate, LocalDateTime modifiedDate, String createdBy, String modifiedBy, Integer isDeleted, String name, String module, String fullName, Integer level, Integer isEnabled) {
        super(SystemPermissionInfo.SYSTEM_PERMISSION_INFO);

        setId(id);
        setCreatedDate(createdDate);
        setModifiedDate(modifiedDate);
        setCreatedBy(createdBy);
        setModifiedBy(modifiedBy);
        setIsDeleted(isDeleted);
        setName(name);
        setModule(module);
        setFullName(fullName);
        setLevel(level);
        setIsEnabled(isEnabled);
    }
}
