/*
 * This file is generated by jOOQ.
 */
package com.example.boot.data.database.jooq.tables.records;


import com.example.boot.data.database.jooq.tables.SystemDataDictGroup;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SystemDataDictGroupRecord extends UpdatableRecordImpl<SystemDataDictGroupRecord> implements Record9<Long, String, LocalDateTime, Integer, Integer, String, LocalDateTime, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>physical_examination_system.system_data_dict_group.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>physical_examination_system.system_data_dict_group.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>physical_examination_system.system_data_dict_group.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>physical_examination_system.system_data_dict_group.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(1);
    }

    /**
     * Setter for <code>physical_examination_system.system_data_dict_group.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>physical_examination_system.system_data_dict_group.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>physical_examination_system.system_data_dict_group.is_deleted</code>.
     */
    public void setIsDeleted(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>physical_examination_system.system_data_dict_group.is_deleted</code>.
     */
    public Integer getIsDeleted() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>physical_examination_system.system_data_dict_group.is_enabled</code>.
     */
    public void setIsEnabled(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>physical_examination_system.system_data_dict_group.is_enabled</code>.
     */
    public Integer getIsEnabled() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>physical_examination_system.system_data_dict_group.modified_by</code>.
     */
    public void setModifiedBy(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>physical_examination_system.system_data_dict_group.modified_by</code>.
     */
    public String getModifiedBy() {
        return (String) get(5);
    }

    /**
     * Setter for <code>physical_examination_system.system_data_dict_group.modified_date</code>.
     */
    public void setModifiedDate(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>physical_examination_system.system_data_dict_group.modified_date</code>.
     */
    public LocalDateTime getModifiedDate() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>physical_examination_system.system_data_dict_group.name</code>.
     */
    public void setName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>physical_examination_system.system_data_dict_group.name</code>.
     */
    public String getName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>physical_examination_system.system_data_dict_group.value</code>.
     */
    public void setValue(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>physical_examination_system.system_data_dict_group.value</code>.
     */
    public String getValue() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, String, LocalDateTime, Integer, Integer, String, LocalDateTime, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Long, String, LocalDateTime, Integer, Integer, String, LocalDateTime, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return SystemDataDictGroup.SYSTEM_DATA_DICT_GROUP.ID;
    }

    @Override
    public Field<String> field2() {
        return SystemDataDictGroup.SYSTEM_DATA_DICT_GROUP.CREATED_BY;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return SystemDataDictGroup.SYSTEM_DATA_DICT_GROUP.CREATED_DATE;
    }

    @Override
    public Field<Integer> field4() {
        return SystemDataDictGroup.SYSTEM_DATA_DICT_GROUP.IS_DELETED;
    }

    @Override
    public Field<Integer> field5() {
        return SystemDataDictGroup.SYSTEM_DATA_DICT_GROUP.IS_ENABLED;
    }

    @Override
    public Field<String> field6() {
        return SystemDataDictGroup.SYSTEM_DATA_DICT_GROUP.MODIFIED_BY;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return SystemDataDictGroup.SYSTEM_DATA_DICT_GROUP.MODIFIED_DATE;
    }

    @Override
    public Field<String> field8() {
        return SystemDataDictGroup.SYSTEM_DATA_DICT_GROUP.NAME;
    }

    @Override
    public Field<String> field9() {
        return SystemDataDictGroup.SYSTEM_DATA_DICT_GROUP.VALUE;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime component3() {
        return getCreatedDate();
    }

    @Override
    public Integer component4() {
        return getIsDeleted();
    }

    @Override
    public Integer component5() {
        return getIsEnabled();
    }

    @Override
    public String component6() {
        return getModifiedBy();
    }

    @Override
    public LocalDateTime component7() {
        return getModifiedDate();
    }

    @Override
    public String component8() {
        return getName();
    }

    @Override
    public String component9() {
        return getValue();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime value3() {
        return getCreatedDate();
    }

    @Override
    public Integer value4() {
        return getIsDeleted();
    }

    @Override
    public Integer value5() {
        return getIsEnabled();
    }

    @Override
    public String value6() {
        return getModifiedBy();
    }

    @Override
    public LocalDateTime value7() {
        return getModifiedDate();
    }

    @Override
    public String value8() {
        return getName();
    }

    @Override
    public String value9() {
        return getValue();
    }

    @Override
    public SystemDataDictGroupRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public SystemDataDictGroupRecord value2(String value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public SystemDataDictGroupRecord value3(LocalDateTime value) {
        setCreatedDate(value);
        return this;
    }

    @Override
    public SystemDataDictGroupRecord value4(Integer value) {
        setIsDeleted(value);
        return this;
    }

    @Override
    public SystemDataDictGroupRecord value5(Integer value) {
        setIsEnabled(value);
        return this;
    }

    @Override
    public SystemDataDictGroupRecord value6(String value) {
        setModifiedBy(value);
        return this;
    }

    @Override
    public SystemDataDictGroupRecord value7(LocalDateTime value) {
        setModifiedDate(value);
        return this;
    }

    @Override
    public SystemDataDictGroupRecord value8(String value) {
        setName(value);
        return this;
    }

    @Override
    public SystemDataDictGroupRecord value9(String value) {
        setValue(value);
        return this;
    }

    @Override
    public SystemDataDictGroupRecord values(Long value1, String value2, LocalDateTime value3, Integer value4, Integer value5, String value6, LocalDateTime value7, String value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SystemDataDictGroupRecord
     */
    public SystemDataDictGroupRecord() {
        super(SystemDataDictGroup.SYSTEM_DATA_DICT_GROUP);
    }

    /**
     * Create a detached, initialised SystemDataDictGroupRecord
     */
    public SystemDataDictGroupRecord(Long id, String createdBy, LocalDateTime createdDate, Integer isDeleted, Integer isEnabled, String modifiedBy, LocalDateTime modifiedDate, String name, String value) {
        super(SystemDataDictGroup.SYSTEM_DATA_DICT_GROUP);

        setId(id);
        setCreatedBy(createdBy);
        setCreatedDate(createdDate);
        setIsDeleted(isDeleted);
        setIsEnabled(isEnabled);
        setModifiedBy(modifiedBy);
        setModifiedDate(modifiedDate);
        setName(name);
        setValue(value);
    }
}
