/*
 * This file is generated by jOOQ.
 */
package com.example.boot.data.database.jooq.tables.records;


import com.example.boot.data.database.jooq.tables.SystemRolesInfo;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SystemRolesInfoRecord extends UpdatableRecordImpl<SystemRolesInfoRecord> implements Record8<Long, String, LocalDateTime, Integer, Integer, String, LocalDateTime, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>physical_examination_system.system_roles_info.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>physical_examination_system.system_roles_info.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>physical_examination_system.system_roles_info.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>physical_examination_system.system_roles_info.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(1);
    }

    /**
     * Setter for <code>physical_examination_system.system_roles_info.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>physical_examination_system.system_roles_info.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>physical_examination_system.system_roles_info.is_deleted</code>.
     */
    public void setIsDeleted(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>physical_examination_system.system_roles_info.is_deleted</code>.
     */
    public Integer getIsDeleted() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>physical_examination_system.system_roles_info.is_enabled</code>.
     */
    public void setIsEnabled(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>physical_examination_system.system_roles_info.is_enabled</code>.
     */
    public Integer getIsEnabled() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>physical_examination_system.system_roles_info.modified_by</code>.
     */
    public void setModifiedBy(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>physical_examination_system.system_roles_info.modified_by</code>.
     */
    public String getModifiedBy() {
        return (String) get(5);
    }

    /**
     * Setter for <code>physical_examination_system.system_roles_info.modified_date</code>.
     */
    public void setModifiedDate(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>physical_examination_system.system_roles_info.modified_date</code>.
     */
    public LocalDateTime getModifiedDate() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>physical_examination_system.system_roles_info.name</code>.
     */
    public void setName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>physical_examination_system.system_roles_info.name</code>.
     */
    public String getName() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, String, LocalDateTime, Integer, Integer, String, LocalDateTime, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Long, String, LocalDateTime, Integer, Integer, String, LocalDateTime, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return SystemRolesInfo.SYSTEM_ROLES_INFO.ID;
    }

    @Override
    public Field<String> field2() {
        return SystemRolesInfo.SYSTEM_ROLES_INFO.CREATED_BY;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return SystemRolesInfo.SYSTEM_ROLES_INFO.CREATED_DATE;
    }

    @Override
    public Field<Integer> field4() {
        return SystemRolesInfo.SYSTEM_ROLES_INFO.IS_DELETED;
    }

    @Override
    public Field<Integer> field5() {
        return SystemRolesInfo.SYSTEM_ROLES_INFO.IS_ENABLED;
    }

    @Override
    public Field<String> field6() {
        return SystemRolesInfo.SYSTEM_ROLES_INFO.MODIFIED_BY;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return SystemRolesInfo.SYSTEM_ROLES_INFO.MODIFIED_DATE;
    }

    @Override
    public Field<String> field8() {
        return SystemRolesInfo.SYSTEM_ROLES_INFO.NAME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime component3() {
        return getCreatedDate();
    }

    @Override
    public Integer component4() {
        return getIsDeleted();
    }

    @Override
    public Integer component5() {
        return getIsEnabled();
    }

    @Override
    public String component6() {
        return getModifiedBy();
    }

    @Override
    public LocalDateTime component7() {
        return getModifiedDate();
    }

    @Override
    public String component8() {
        return getName();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime value3() {
        return getCreatedDate();
    }

    @Override
    public Integer value4() {
        return getIsDeleted();
    }

    @Override
    public Integer value5() {
        return getIsEnabled();
    }

    @Override
    public String value6() {
        return getModifiedBy();
    }

    @Override
    public LocalDateTime value7() {
        return getModifiedDate();
    }

    @Override
    public String value8() {
        return getName();
    }

    @Override
    public SystemRolesInfoRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public SystemRolesInfoRecord value2(String value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public SystemRolesInfoRecord value3(LocalDateTime value) {
        setCreatedDate(value);
        return this;
    }

    @Override
    public SystemRolesInfoRecord value4(Integer value) {
        setIsDeleted(value);
        return this;
    }

    @Override
    public SystemRolesInfoRecord value5(Integer value) {
        setIsEnabled(value);
        return this;
    }

    @Override
    public SystemRolesInfoRecord value6(String value) {
        setModifiedBy(value);
        return this;
    }

    @Override
    public SystemRolesInfoRecord value7(LocalDateTime value) {
        setModifiedDate(value);
        return this;
    }

    @Override
    public SystemRolesInfoRecord value8(String value) {
        setName(value);
        return this;
    }

    @Override
    public SystemRolesInfoRecord values(Long value1, String value2, LocalDateTime value3, Integer value4, Integer value5, String value6, LocalDateTime value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SystemRolesInfoRecord
     */
    public SystemRolesInfoRecord() {
        super(SystemRolesInfo.SYSTEM_ROLES_INFO);
    }

    /**
     * Create a detached, initialised SystemRolesInfoRecord
     */
    public SystemRolesInfoRecord(Long id, String createdBy, LocalDateTime createdDate, Integer isDeleted, Integer isEnabled, String modifiedBy, LocalDateTime modifiedDate, String name) {
        super(SystemRolesInfo.SYSTEM_ROLES_INFO);

        setId(id);
        setCreatedBy(createdBy);
        setCreatedDate(createdDate);
        setIsDeleted(isDeleted);
        setIsEnabled(isEnabled);
        setModifiedBy(modifiedBy);
        setModifiedDate(modifiedDate);
        setName(name);
    }
}
