/*
 * This file is generated by jOOQ.
 */
package com.example.boot.data.database.jooq.tables.records;


import com.example.boot.data.database.jooq.tables.TeamMealInfo;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 团队套餐信息
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeamMealInfoRecord extends UpdatableRecordImpl<TeamMealInfoRecord> implements Record17<Long, LocalDateTime, LocalDateTime, String, String, Integer, Long, String, Long, String, String, Long, String, String, BigDecimal, BigDecimal, BigDecimal> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>physical_examination_system.team_meal_info.id</code>. id
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>physical_examination_system.team_meal_info.id</code>. id
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>physical_examination_system.team_meal_info.created_date</code>. createdDate
     */
    public void setCreatedDate(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>physical_examination_system.team_meal_info.created_date</code>. createdDate
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>physical_examination_system.team_meal_info.modified_date</code>. modifiedDate
     */
    public void setModifiedDate(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>physical_examination_system.team_meal_info.modified_date</code>. modifiedDate
     */
    public LocalDateTime getModifiedDate() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>physical_examination_system.team_meal_info.created_by</code>. createdBy
     */
    public void setCreatedBy(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>physical_examination_system.team_meal_info.created_by</code>. createdBy
     */
    public String getCreatedBy() {
        return (String) get(3);
    }

    /**
     * Setter for <code>physical_examination_system.team_meal_info.modified_by</code>. modifiedBy
     */
    public void setModifiedBy(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>physical_examination_system.team_meal_info.modified_by</code>. modifiedBy
     */
    public String getModifiedBy() {
        return (String) get(4);
    }

    /**
     * Setter for <code>physical_examination_system.team_meal_info.is_deleted</code>. isDeleted
     */
    public void setIsDeleted(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>physical_examination_system.team_meal_info.is_deleted</code>. isDeleted
     */
    public Integer getIsDeleted() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>physical_examination_system.team_meal_info.customer_id</code>. 客户ID
     */
    public void setCustomerId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>physical_examination_system.team_meal_info.customer_id</code>. 客户ID
     */
    public Long getCustomerId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>physical_examination_system.team_meal_info.customer_name</code>. 客户名称
     */
    public void setCustomerName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>physical_examination_system.team_meal_info.customer_name</code>. 客户名称
     */
    public String getCustomerName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>physical_examination_system.team_meal_info.team_id</code>. 团队ID
     */
    public void setTeamId(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>physical_examination_system.team_meal_info.team_id</code>. 团队ID
     */
    public Long getTeamId() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>physical_examination_system.team_meal_info.code</code>. 团队编号
     */
    public void setCode(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>physical_examination_system.team_meal_info.code</code>. 团队编号
     */
    public String getCode() {
        return (String) get(9);
    }

    /**
     * Setter for <code>physical_examination_system.team_meal_info.name</code>. 团队名称
     */
    public void setName(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>physical_examination_system.team_meal_info.name</code>. 团队名称
     */
    public String getName() {
        return (String) get(10);
    }

    /**
     * Setter for <code>physical_examination_system.team_meal_info.meal_id</code>. 套餐ID
     */
    public void setMealId(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>physical_examination_system.team_meal_info.meal_id</code>. 套餐ID
     */
    public Long getMealId() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>physical_examination_system.team_meal_info.meal_code</code>. 套餐编号
     */
    public void setMealCode(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>physical_examination_system.team_meal_info.meal_code</code>. 套餐编号
     */
    public String getMealCode() {
        return (String) get(12);
    }

    /**
     * Setter for <code>physical_examination_system.team_meal_info.meal_name</code>. 套餐名称
     */
    public void setMealName(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>physical_examination_system.team_meal_info.meal_name</code>. 套餐名称
     */
    public String getMealName() {
        return (String) get(13);
    }

    /**
     * Setter for <code>physical_examination_system.team_meal_info.meal_price</code>. 套餐价格
     */
    public void setMealPrice(BigDecimal value) {
        set(14, value);
    }

    /**
     * Getter for <code>physical_examination_system.team_meal_info.meal_price</code>. 套餐价格
     */
    public BigDecimal getMealPrice() {
        return (BigDecimal) get(14);
    }

    /**
     * Setter for <code>physical_examination_system.team_meal_info.meal_discount_rate</code>. 套餐折扣率
     */
    public void setMealDiscountRate(BigDecimal value) {
        set(15, value);
    }

    /**
     * Getter for <code>physical_examination_system.team_meal_info.meal_discount_rate</code>. 套餐折扣率
     */
    public BigDecimal getMealDiscountRate() {
        return (BigDecimal) get(15);
    }

    /**
     * Setter for <code>physical_examination_system.team_meal_info.meal_discount_price</code>. 套餐折扣价
     */
    public void setMealDiscountPrice(BigDecimal value) {
        set(16, value);
    }

    /**
     * Getter for <code>physical_examination_system.team_meal_info.meal_discount_price</code>. 套餐折扣价
     */
    public BigDecimal getMealDiscountPrice() {
        return (BigDecimal) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row17<Long, LocalDateTime, LocalDateTime, String, String, Integer, Long, String, Long, String, String, Long, String, String, BigDecimal, BigDecimal, BigDecimal> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    @Override
    public Row17<Long, LocalDateTime, LocalDateTime, String, String, Integer, Long, String, Long, String, String, Long, String, String, BigDecimal, BigDecimal, BigDecimal> valuesRow() {
        return (Row17) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return TeamMealInfo.TEAM_MEAL_INFO.ID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return TeamMealInfo.TEAM_MEAL_INFO.CREATED_DATE;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return TeamMealInfo.TEAM_MEAL_INFO.MODIFIED_DATE;
    }

    @Override
    public Field<String> field4() {
        return TeamMealInfo.TEAM_MEAL_INFO.CREATED_BY;
    }

    @Override
    public Field<String> field5() {
        return TeamMealInfo.TEAM_MEAL_INFO.MODIFIED_BY;
    }

    @Override
    public Field<Integer> field6() {
        return TeamMealInfo.TEAM_MEAL_INFO.IS_DELETED;
    }

    @Override
    public Field<Long> field7() {
        return TeamMealInfo.TEAM_MEAL_INFO.CUSTOMER_ID;
    }

    @Override
    public Field<String> field8() {
        return TeamMealInfo.TEAM_MEAL_INFO.CUSTOMER_NAME;
    }

    @Override
    public Field<Long> field9() {
        return TeamMealInfo.TEAM_MEAL_INFO.TEAM_ID;
    }

    @Override
    public Field<String> field10() {
        return TeamMealInfo.TEAM_MEAL_INFO.CODE;
    }

    @Override
    public Field<String> field11() {
        return TeamMealInfo.TEAM_MEAL_INFO.NAME;
    }

    @Override
    public Field<Long> field12() {
        return TeamMealInfo.TEAM_MEAL_INFO.MEAL_ID;
    }

    @Override
    public Field<String> field13() {
        return TeamMealInfo.TEAM_MEAL_INFO.MEAL_CODE;
    }

    @Override
    public Field<String> field14() {
        return TeamMealInfo.TEAM_MEAL_INFO.MEAL_NAME;
    }

    @Override
    public Field<BigDecimal> field15() {
        return TeamMealInfo.TEAM_MEAL_INFO.MEAL_PRICE;
    }

    @Override
    public Field<BigDecimal> field16() {
        return TeamMealInfo.TEAM_MEAL_INFO.MEAL_DISCOUNT_RATE;
    }

    @Override
    public Field<BigDecimal> field17() {
        return TeamMealInfo.TEAM_MEAL_INFO.MEAL_DISCOUNT_PRICE;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public LocalDateTime component2() {
        return getCreatedDate();
    }

    @Override
    public LocalDateTime component3() {
        return getModifiedDate();
    }

    @Override
    public String component4() {
        return getCreatedBy();
    }

    @Override
    public String component5() {
        return getModifiedBy();
    }

    @Override
    public Integer component6() {
        return getIsDeleted();
    }

    @Override
    public Long component7() {
        return getCustomerId();
    }

    @Override
    public String component8() {
        return getCustomerName();
    }

    @Override
    public Long component9() {
        return getTeamId();
    }

    @Override
    public String component10() {
        return getCode();
    }

    @Override
    public String component11() {
        return getName();
    }

    @Override
    public Long component12() {
        return getMealId();
    }

    @Override
    public String component13() {
        return getMealCode();
    }

    @Override
    public String component14() {
        return getMealName();
    }

    @Override
    public BigDecimal component15() {
        return getMealPrice();
    }

    @Override
    public BigDecimal component16() {
        return getMealDiscountRate();
    }

    @Override
    public BigDecimal component17() {
        return getMealDiscountPrice();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public LocalDateTime value2() {
        return getCreatedDate();
    }

    @Override
    public LocalDateTime value3() {
        return getModifiedDate();
    }

    @Override
    public String value4() {
        return getCreatedBy();
    }

    @Override
    public String value5() {
        return getModifiedBy();
    }

    @Override
    public Integer value6() {
        return getIsDeleted();
    }

    @Override
    public Long value7() {
        return getCustomerId();
    }

    @Override
    public String value8() {
        return getCustomerName();
    }

    @Override
    public Long value9() {
        return getTeamId();
    }

    @Override
    public String value10() {
        return getCode();
    }

    @Override
    public String value11() {
        return getName();
    }

    @Override
    public Long value12() {
        return getMealId();
    }

    @Override
    public String value13() {
        return getMealCode();
    }

    @Override
    public String value14() {
        return getMealName();
    }

    @Override
    public BigDecimal value15() {
        return getMealPrice();
    }

    @Override
    public BigDecimal value16() {
        return getMealDiscountRate();
    }

    @Override
    public BigDecimal value17() {
        return getMealDiscountPrice();
    }

    @Override
    public TeamMealInfoRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public TeamMealInfoRecord value2(LocalDateTime value) {
        setCreatedDate(value);
        return this;
    }

    @Override
    public TeamMealInfoRecord value3(LocalDateTime value) {
        setModifiedDate(value);
        return this;
    }

    @Override
    public TeamMealInfoRecord value4(String value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public TeamMealInfoRecord value5(String value) {
        setModifiedBy(value);
        return this;
    }

    @Override
    public TeamMealInfoRecord value6(Integer value) {
        setIsDeleted(value);
        return this;
    }

    @Override
    public TeamMealInfoRecord value7(Long value) {
        setCustomerId(value);
        return this;
    }

    @Override
    public TeamMealInfoRecord value8(String value) {
        setCustomerName(value);
        return this;
    }

    @Override
    public TeamMealInfoRecord value9(Long value) {
        setTeamId(value);
        return this;
    }

    @Override
    public TeamMealInfoRecord value10(String value) {
        setCode(value);
        return this;
    }

    @Override
    public TeamMealInfoRecord value11(String value) {
        setName(value);
        return this;
    }

    @Override
    public TeamMealInfoRecord value12(Long value) {
        setMealId(value);
        return this;
    }

    @Override
    public TeamMealInfoRecord value13(String value) {
        setMealCode(value);
        return this;
    }

    @Override
    public TeamMealInfoRecord value14(String value) {
        setMealName(value);
        return this;
    }

    @Override
    public TeamMealInfoRecord value15(BigDecimal value) {
        setMealPrice(value);
        return this;
    }

    @Override
    public TeamMealInfoRecord value16(BigDecimal value) {
        setMealDiscountRate(value);
        return this;
    }

    @Override
    public TeamMealInfoRecord value17(BigDecimal value) {
        setMealDiscountPrice(value);
        return this;
    }

    @Override
    public TeamMealInfoRecord values(Long value1, LocalDateTime value2, LocalDateTime value3, String value4, String value5, Integer value6, Long value7, String value8, Long value9, String value10, String value11, Long value12, String value13, String value14, BigDecimal value15, BigDecimal value16, BigDecimal value17) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TeamMealInfoRecord
     */
    public TeamMealInfoRecord() {
        super(TeamMealInfo.TEAM_MEAL_INFO);
    }

    /**
     * Create a detached, initialised TeamMealInfoRecord
     */
    public TeamMealInfoRecord(Long id, LocalDateTime createdDate, LocalDateTime modifiedDate, String createdBy, String modifiedBy, Integer isDeleted, Long customerId, String customerName, Long teamId, String code, String name, Long mealId, String mealCode, String mealName, BigDecimal mealPrice, BigDecimal mealDiscountRate, BigDecimal mealDiscountPrice) {
        super(TeamMealInfo.TEAM_MEAL_INFO);

        setId(id);
        setCreatedDate(createdDate);
        setModifiedDate(modifiedDate);
        setCreatedBy(createdBy);
        setModifiedBy(modifiedBy);
        setIsDeleted(isDeleted);
        setCustomerId(customerId);
        setCustomerName(customerName);
        setTeamId(teamId);
        setCode(code);
        setName(name);
        setMealId(mealId);
        setMealCode(mealCode);
        setMealName(mealName);
        setMealPrice(mealPrice);
        setMealDiscountRate(mealDiscountRate);
        setMealDiscountPrice(mealDiscountPrice);
    }
}
