/*
 * This file is generated by jOOQ.
 */
package com.example.boot.data.database.jooq.tables.records;


import com.example.boot.data.database.jooq.tables.TeamPatientInfo;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record18;
import org.jooq.Row18;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 团队人员信息
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeamPatientInfoRecord extends UpdatableRecordImpl<TeamPatientInfoRecord> implements Record18<Long, LocalDateTime, LocalDateTime, String, String, Integer, Long, String, Long, String, String, Long, String, String, String, String, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>physical_examination_system.team_patient_info.id</code>. id
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>physical_examination_system.team_patient_info.id</code>. id
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>physical_examination_system.team_patient_info.created_date</code>. createdDate
     */
    public void setCreatedDate(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>physical_examination_system.team_patient_info.created_date</code>. createdDate
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>physical_examination_system.team_patient_info.modified_date</code>. modifiedDate
     */
    public void setModifiedDate(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>physical_examination_system.team_patient_info.modified_date</code>. modifiedDate
     */
    public LocalDateTime getModifiedDate() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>physical_examination_system.team_patient_info.created_by</code>. createdBy
     */
    public void setCreatedBy(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>physical_examination_system.team_patient_info.created_by</code>. createdBy
     */
    public String getCreatedBy() {
        return (String) get(3);
    }

    /**
     * Setter for <code>physical_examination_system.team_patient_info.modified_by</code>. modifiedBy
     */
    public void setModifiedBy(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>physical_examination_system.team_patient_info.modified_by</code>. modifiedBy
     */
    public String getModifiedBy() {
        return (String) get(4);
    }

    /**
     * Setter for <code>physical_examination_system.team_patient_info.is_deleted</code>. isDeleted
     */
    public void setIsDeleted(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>physical_examination_system.team_patient_info.is_deleted</code>. isDeleted
     */
    public Integer getIsDeleted() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>physical_examination_system.team_patient_info.customer_id</code>. 客户ID
     */
    public void setCustomerId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>physical_examination_system.team_patient_info.customer_id</code>. 客户ID
     */
    public Long getCustomerId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>physical_examination_system.team_patient_info.customer_name</code>. 客户名称
     */
    public void setCustomerName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>physical_examination_system.team_patient_info.customer_name</code>. 客户名称
     */
    public String getCustomerName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>physical_examination_system.team_patient_info.team_id</code>. 团体ID
     */
    public void setTeamId(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>physical_examination_system.team_patient_info.team_id</code>. 团体ID
     */
    public Long getTeamId() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>physical_examination_system.team_patient_info.team_code</code>. 团队编号
     */
    public void setTeamCode(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>physical_examination_system.team_patient_info.team_code</code>. 团队编号
     */
    public String getTeamCode() {
        return (String) get(9);
    }

    /**
     * Setter for <code>physical_examination_system.team_patient_info.team_name</code>. 团队名称
     */
    public void setTeamName(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>physical_examination_system.team_patient_info.team_name</code>. 团队名称
     */
    public String getTeamName() {
        return (String) get(10);
    }

    /**
     * Setter for <code>physical_examination_system.team_patient_info.patient_id</code>. 体检人ID
     */
    public void setPatientId(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>physical_examination_system.team_patient_info.patient_id</code>. 体检人ID
     */
    public Long getPatientId() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>physical_examination_system.team_patient_info.patient_code</code>. 体检人编号
     */
    public void setPatientCode(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>physical_examination_system.team_patient_info.patient_code</code>. 体检人编号
     */
    public String getPatientCode() {
        return (String) get(12);
    }

    /**
     * Setter for <code>physical_examination_system.team_patient_info.patient_name</code>. 体检人姓名
     */
    public void setPatientName(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>physical_examination_system.team_patient_info.patient_name</code>. 体检人姓名
     */
    public String getPatientName() {
        return (String) get(13);
    }

    /**
     * Setter for <code>physical_examination_system.team_patient_info.patient_id_card</code>. 体检人证件号
     */
    public void setPatientIdCard(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>physical_examination_system.team_patient_info.patient_id_card</code>. 体检人证件号
     */
    public String getPatientIdCard() {
        return (String) get(14);
    }

    /**
     * Setter for <code>physical_examination_system.team_patient_info.patient_gender</code>. 体检人性别
     */
    public void setPatientGender(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>physical_examination_system.team_patient_info.patient_gender</code>. 体检人性别
     */
    public String getPatientGender() {
        return (String) get(15);
    }

    /**
     * Setter for <code>physical_examination_system.team_patient_info.patient_age</code>. 体检人年龄
     */
    public void setPatientAge(Integer value) {
        set(16, value);
    }

    /**
     * Getter for <code>physical_examination_system.team_patient_info.patient_age</code>. 体检人年龄
     */
    public Integer getPatientAge() {
        return (Integer) get(16);
    }

    /**
     * Setter for <code>physical_examination_system.team_patient_info.patient_status</code>. 体检人状态
     */
    public void setPatientStatus(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>physical_examination_system.team_patient_info.patient_status</code>. 体检人状态
     */
    public Integer getPatientStatus() {
        return (Integer) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record18 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row18<Long, LocalDateTime, LocalDateTime, String, String, Integer, Long, String, Long, String, String, Long, String, String, String, String, Integer, Integer> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    @Override
    public Row18<Long, LocalDateTime, LocalDateTime, String, String, Integer, Long, String, Long, String, String, Long, String, String, String, String, Integer, Integer> valuesRow() {
        return (Row18) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return TeamPatientInfo.TEAM_PATIENT_INFO.ID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return TeamPatientInfo.TEAM_PATIENT_INFO.CREATED_DATE;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return TeamPatientInfo.TEAM_PATIENT_INFO.MODIFIED_DATE;
    }

    @Override
    public Field<String> field4() {
        return TeamPatientInfo.TEAM_PATIENT_INFO.CREATED_BY;
    }

    @Override
    public Field<String> field5() {
        return TeamPatientInfo.TEAM_PATIENT_INFO.MODIFIED_BY;
    }

    @Override
    public Field<Integer> field6() {
        return TeamPatientInfo.TEAM_PATIENT_INFO.IS_DELETED;
    }

    @Override
    public Field<Long> field7() {
        return TeamPatientInfo.TEAM_PATIENT_INFO.CUSTOMER_ID;
    }

    @Override
    public Field<String> field8() {
        return TeamPatientInfo.TEAM_PATIENT_INFO.CUSTOMER_NAME;
    }

    @Override
    public Field<Long> field9() {
        return TeamPatientInfo.TEAM_PATIENT_INFO.TEAM_ID;
    }

    @Override
    public Field<String> field10() {
        return TeamPatientInfo.TEAM_PATIENT_INFO.TEAM_CODE;
    }

    @Override
    public Field<String> field11() {
        return TeamPatientInfo.TEAM_PATIENT_INFO.TEAM_NAME;
    }

    @Override
    public Field<Long> field12() {
        return TeamPatientInfo.TEAM_PATIENT_INFO.PATIENT_ID;
    }

    @Override
    public Field<String> field13() {
        return TeamPatientInfo.TEAM_PATIENT_INFO.PATIENT_CODE;
    }

    @Override
    public Field<String> field14() {
        return TeamPatientInfo.TEAM_PATIENT_INFO.PATIENT_NAME;
    }

    @Override
    public Field<String> field15() {
        return TeamPatientInfo.TEAM_PATIENT_INFO.PATIENT_ID_CARD;
    }

    @Override
    public Field<String> field16() {
        return TeamPatientInfo.TEAM_PATIENT_INFO.PATIENT_GENDER;
    }

    @Override
    public Field<Integer> field17() {
        return TeamPatientInfo.TEAM_PATIENT_INFO.PATIENT_AGE;
    }

    @Override
    public Field<Integer> field18() {
        return TeamPatientInfo.TEAM_PATIENT_INFO.PATIENT_STATUS;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public LocalDateTime component2() {
        return getCreatedDate();
    }

    @Override
    public LocalDateTime component3() {
        return getModifiedDate();
    }

    @Override
    public String component4() {
        return getCreatedBy();
    }

    @Override
    public String component5() {
        return getModifiedBy();
    }

    @Override
    public Integer component6() {
        return getIsDeleted();
    }

    @Override
    public Long component7() {
        return getCustomerId();
    }

    @Override
    public String component8() {
        return getCustomerName();
    }

    @Override
    public Long component9() {
        return getTeamId();
    }

    @Override
    public String component10() {
        return getTeamCode();
    }

    @Override
    public String component11() {
        return getTeamName();
    }

    @Override
    public Long component12() {
        return getPatientId();
    }

    @Override
    public String component13() {
        return getPatientCode();
    }

    @Override
    public String component14() {
        return getPatientName();
    }

    @Override
    public String component15() {
        return getPatientIdCard();
    }

    @Override
    public String component16() {
        return getPatientGender();
    }

    @Override
    public Integer component17() {
        return getPatientAge();
    }

    @Override
    public Integer component18() {
        return getPatientStatus();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public LocalDateTime value2() {
        return getCreatedDate();
    }

    @Override
    public LocalDateTime value3() {
        return getModifiedDate();
    }

    @Override
    public String value4() {
        return getCreatedBy();
    }

    @Override
    public String value5() {
        return getModifiedBy();
    }

    @Override
    public Integer value6() {
        return getIsDeleted();
    }

    @Override
    public Long value7() {
        return getCustomerId();
    }

    @Override
    public String value8() {
        return getCustomerName();
    }

    @Override
    public Long value9() {
        return getTeamId();
    }

    @Override
    public String value10() {
        return getTeamCode();
    }

    @Override
    public String value11() {
        return getTeamName();
    }

    @Override
    public Long value12() {
        return getPatientId();
    }

    @Override
    public String value13() {
        return getPatientCode();
    }

    @Override
    public String value14() {
        return getPatientName();
    }

    @Override
    public String value15() {
        return getPatientIdCard();
    }

    @Override
    public String value16() {
        return getPatientGender();
    }

    @Override
    public Integer value17() {
        return getPatientAge();
    }

    @Override
    public Integer value18() {
        return getPatientStatus();
    }

    @Override
    public TeamPatientInfoRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public TeamPatientInfoRecord value2(LocalDateTime value) {
        setCreatedDate(value);
        return this;
    }

    @Override
    public TeamPatientInfoRecord value3(LocalDateTime value) {
        setModifiedDate(value);
        return this;
    }

    @Override
    public TeamPatientInfoRecord value4(String value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public TeamPatientInfoRecord value5(String value) {
        setModifiedBy(value);
        return this;
    }

    @Override
    public TeamPatientInfoRecord value6(Integer value) {
        setIsDeleted(value);
        return this;
    }

    @Override
    public TeamPatientInfoRecord value7(Long value) {
        setCustomerId(value);
        return this;
    }

    @Override
    public TeamPatientInfoRecord value8(String value) {
        setCustomerName(value);
        return this;
    }

    @Override
    public TeamPatientInfoRecord value9(Long value) {
        setTeamId(value);
        return this;
    }

    @Override
    public TeamPatientInfoRecord value10(String value) {
        setTeamCode(value);
        return this;
    }

    @Override
    public TeamPatientInfoRecord value11(String value) {
        setTeamName(value);
        return this;
    }

    @Override
    public TeamPatientInfoRecord value12(Long value) {
        setPatientId(value);
        return this;
    }

    @Override
    public TeamPatientInfoRecord value13(String value) {
        setPatientCode(value);
        return this;
    }

    @Override
    public TeamPatientInfoRecord value14(String value) {
        setPatientName(value);
        return this;
    }

    @Override
    public TeamPatientInfoRecord value15(String value) {
        setPatientIdCard(value);
        return this;
    }

    @Override
    public TeamPatientInfoRecord value16(String value) {
        setPatientGender(value);
        return this;
    }

    @Override
    public TeamPatientInfoRecord value17(Integer value) {
        setPatientAge(value);
        return this;
    }

    @Override
    public TeamPatientInfoRecord value18(Integer value) {
        setPatientStatus(value);
        return this;
    }

    @Override
    public TeamPatientInfoRecord values(Long value1, LocalDateTime value2, LocalDateTime value3, String value4, String value5, Integer value6, Long value7, String value8, Long value9, String value10, String value11, Long value12, String value13, String value14, String value15, String value16, Integer value17, Integer value18) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TeamPatientInfoRecord
     */
    public TeamPatientInfoRecord() {
        super(TeamPatientInfo.TEAM_PATIENT_INFO);
    }

    /**
     * Create a detached, initialised TeamPatientInfoRecord
     */
    public TeamPatientInfoRecord(Long id, LocalDateTime createdDate, LocalDateTime modifiedDate, String createdBy, String modifiedBy, Integer isDeleted, Long customerId, String customerName, Long teamId, String teamCode, String teamName, Long patientId, String patientCode, String patientName, String patientIdCard, String patientGender, Integer patientAge, Integer patientStatus) {
        super(TeamPatientInfo.TEAM_PATIENT_INFO);

        setId(id);
        setCreatedDate(createdDate);
        setModifiedDate(modifiedDate);
        setCreatedBy(createdBy);
        setModifiedBy(modifiedBy);
        setIsDeleted(isDeleted);
        setCustomerId(customerId);
        setCustomerName(customerName);
        setTeamId(teamId);
        setTeamCode(teamCode);
        setTeamName(teamName);
        setPatientId(patientId);
        setPatientCode(patientCode);
        setPatientName(patientName);
        setPatientIdCard(patientIdCard);
        setPatientGender(patientGender);
        setPatientAge(patientAge);
        setPatientStatus(patientStatus);
    }
}
