/*
 * This file is generated by jOOQ.
 */
package com.example.boot.data.database.jooq.tables;


import com.example.boot.data.database.jooq.Keys;
import com.example.boot.data.database.jooq.PhysicalExaminationSystem;
import com.example.boot.data.database.jooq.tables.records.GoodsInfoRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row10;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 商品信息
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GoodsInfo extends TableImpl<GoodsInfoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>physical_examination_system.goods_info</code>
     */
    public static final GoodsInfo GOODS_INFO = new GoodsInfo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GoodsInfoRecord> getRecordType() {
        return GoodsInfoRecord.class;
    }

    /**
     * The column <code>physical_examination_system.goods_info.id</code>. id
     */
    public final TableField<GoodsInfoRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "id");

    /**
     * The column <code>physical_examination_system.goods_info.created_date</code>. createdDate
     */
    public final TableField<GoodsInfoRecord, LocalDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("1000-01-01 00:00:00", SQLDataType.LOCALDATETIME)), this, "createdDate");

    /**
     * The column <code>physical_examination_system.goods_info.modified_date</code>. modifiedDate
     */
    public final TableField<GoodsInfoRecord, LocalDateTime> MODIFIED_DATE = createField(DSL.name("modified_date"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.inline("1000-01-01 00:00:00", SQLDataType.LOCALDATETIME)), this, "modifiedDate");

    /**
     * The column <code>physical_examination_system.goods_info.created_by</code>. createdBy
     */
    public final TableField<GoodsInfoRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(50).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "createdBy");

    /**
     * The column <code>physical_examination_system.goods_info.modified_by</code>. modifiedBy
     */
    public final TableField<GoodsInfoRecord, String> MODIFIED_BY = createField(DSL.name("modified_by"), SQLDataType.VARCHAR(50).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "modifiedBy");

    /**
     * The column <code>physical_examination_system.goods_info.is_deleted</code>. isDeleted
     */
    public final TableField<GoodsInfoRecord, Integer> IS_DELETED = createField(DSL.name("is_deleted"), SQLDataType.INTEGER.defaultValue(DSL.inline("-1", SQLDataType.INTEGER)), this, "isDeleted");

    /**
     * The column <code>physical_examination_system.goods_info.type</code>. 商品类型
     */
    public final TableField<GoodsInfoRecord, Integer> TYPE = createField(DSL.name("type"), SQLDataType.INTEGER.defaultValue(DSL.inline("-1", SQLDataType.INTEGER)), this, "商品类型");

    /**
     * The column <code>physical_examination_system.goods_info.code</code>. 商品编号
     */
    public final TableField<GoodsInfoRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(50).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "商品编号");

    /**
     * The column <code>physical_examination_system.goods_info.name</code>. 商品名称
     */
    public final TableField<GoodsInfoRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(50).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "商品名称");

    /**
     * The column <code>physical_examination_system.goods_info.price</code>. 商品单价
     */
    public final TableField<GoodsInfoRecord, BigDecimal> PRICE = createField(DSL.name("price"), SQLDataType.DECIMAL(13, 4).defaultValue(DSL.inline("-1.0000", SQLDataType.DECIMAL)), this, "商品单价");

    private GoodsInfo(Name alias, Table<GoodsInfoRecord> aliased) {
        this(alias, aliased, null);
    }

    private GoodsInfo(Name alias, Table<GoodsInfoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("商品信息"), TableOptions.table());
    }

    /**
     * Create an aliased <code>physical_examination_system.goods_info</code> table reference
     */
    public GoodsInfo(String alias) {
        this(DSL.name(alias), GOODS_INFO);
    }

    /**
     * Create an aliased <code>physical_examination_system.goods_info</code> table reference
     */
    public GoodsInfo(Name alias) {
        this(alias, GOODS_INFO);
    }

    /**
     * Create a <code>physical_examination_system.goods_info</code> table reference
     */
    public GoodsInfo() {
        this(DSL.name("goods_info"), null);
    }

    public <O extends Record> GoodsInfo(Table<O> child, ForeignKey<O, GoodsInfoRecord> key) {
        super(child, key, GOODS_INFO);
    }

    @Override
    public Schema getSchema() {
        return PhysicalExaminationSystem.PHYSICAL_EXAMINATION_SYSTEM;
    }

    @Override
    public Identity<GoodsInfoRecord, Long> getIdentity() {
        return (Identity<GoodsInfoRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<GoodsInfoRecord> getPrimaryKey() {
        return Keys.KEY_GOODS_INFO_PRIMARY;
    }

    @Override
    public List<UniqueKey<GoodsInfoRecord>> getKeys() {
        return Arrays.<UniqueKey<GoodsInfoRecord>>asList(Keys.KEY_GOODS_INFO_PRIMARY);
    }

    @Override
    public GoodsInfo as(String alias) {
        return new GoodsInfo(DSL.name(alias), this);
    }

    @Override
    public GoodsInfo as(Name alias) {
        return new GoodsInfo(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public GoodsInfo rename(String name) {
        return new GoodsInfo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GoodsInfo rename(Name name) {
        return new GoodsInfo(name, null);
    }

    // -------------------------------------------------------------------------
    // Row10 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, LocalDateTime, LocalDateTime, String, String, Integer, Integer, String, String, BigDecimal> fieldsRow() {
        return (Row10) super.fieldsRow();
    }
}
