/*
 * This file is generated by jOOQ.
 */
package com.example.boot.data.database.jooq.tables;


import com.example.boot.data.database.jooq.Keys;
import com.example.boot.data.database.jooq.PhysicalExaminationSystem;
import com.example.boot.data.database.jooq.tables.records.PatientSingleConclusionInfoRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row14;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PatientSingleConclusionInfo extends TableImpl<PatientSingleConclusionInfoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>physical_examination_system.patient_single_conclusion_info</code>
     */
    public static final PatientSingleConclusionInfo PATIENT_SINGLE_CONCLUSION_INFO = new PatientSingleConclusionInfo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PatientSingleConclusionInfoRecord> getRecordType() {
        return PatientSingleConclusionInfoRecord.class;
    }

    /**
     * The column <code>physical_examination_system.patient_single_conclusion_info.id</code>.
     */
    public final TableField<PatientSingleConclusionInfoRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>physical_examination_system.patient_single_conclusion_info.conclusion</code>.
     */
    public final TableField<PatientSingleConclusionInfoRecord, String> CONCLUSION = createField(DSL.name("conclusion"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>physical_examination_system.patient_single_conclusion_info.created_by</code>.
     */
    public final TableField<PatientSingleConclusionInfoRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>physical_examination_system.patient_single_conclusion_info.created_date</code>.
     */
    public final TableField<PatientSingleConclusionInfoRecord, LocalDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>physical_examination_system.patient_single_conclusion_info.fee_item_id</code>.
     */
    public final TableField<PatientSingleConclusionInfoRecord, Long> FEE_ITEM_ID = createField(DSL.name("fee_item_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>physical_examination_system.patient_single_conclusion_info.fee_item_name</code>.
     */
    public final TableField<PatientSingleConclusionInfoRecord, String> FEE_ITEM_NAME = createField(DSL.name("fee_item_name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>physical_examination_system.patient_single_conclusion_info.is_abnormal</code>.
     */
    public final TableField<PatientSingleConclusionInfoRecord, Integer> IS_ABNORMAL = createField(DSL.name("is_abnormal"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>physical_examination_system.patient_single_conclusion_info.is_deleted</code>.
     */
    public final TableField<PatientSingleConclusionInfoRecord, Integer> IS_DELETED = createField(DSL.name("is_deleted"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>physical_examination_system.patient_single_conclusion_info.modified_by</code>.
     */
    public final TableField<PatientSingleConclusionInfoRecord, String> MODIFIED_BY = createField(DSL.name("modified_by"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>physical_examination_system.patient_single_conclusion_info.modified_date</code>.
     */
    public final TableField<PatientSingleConclusionInfoRecord, LocalDateTime> MODIFIED_DATE = createField(DSL.name("modified_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>physical_examination_system.patient_single_conclusion_info.patient_code</code>.
     */
    public final TableField<PatientSingleConclusionInfoRecord, String> PATIENT_CODE = createField(DSL.name("patient_code"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>physical_examination_system.patient_single_conclusion_info.patient_fee_item_id</code>.
     */
    public final TableField<PatientSingleConclusionInfoRecord, Long> PATIENT_FEE_ITEM_ID = createField(DSL.name("patient_fee_item_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>physical_examination_system.patient_single_conclusion_info.patient_fee_item_name</code>.
     */
    public final TableField<PatientSingleConclusionInfoRecord, String> PATIENT_FEE_ITEM_NAME = createField(DSL.name("patient_fee_item_name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>physical_examination_system.patient_single_conclusion_info.patient_id</code>.
     */
    public final TableField<PatientSingleConclusionInfoRecord, Long> PATIENT_ID = createField(DSL.name("patient_id"), SQLDataType.BIGINT, this, "");

    private PatientSingleConclusionInfo(Name alias, Table<PatientSingleConclusionInfoRecord> aliased) {
        this(alias, aliased, null);
    }

    private PatientSingleConclusionInfo(Name alias, Table<PatientSingleConclusionInfoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>physical_examination_system.patient_single_conclusion_info</code> table reference
     */
    public PatientSingleConclusionInfo(String alias) {
        this(DSL.name(alias), PATIENT_SINGLE_CONCLUSION_INFO);
    }

    /**
     * Create an aliased <code>physical_examination_system.patient_single_conclusion_info</code> table reference
     */
    public PatientSingleConclusionInfo(Name alias) {
        this(alias, PATIENT_SINGLE_CONCLUSION_INFO);
    }

    /**
     * Create a <code>physical_examination_system.patient_single_conclusion_info</code> table reference
     */
    public PatientSingleConclusionInfo() {
        this(DSL.name("patient_single_conclusion_info"), null);
    }

    public <O extends Record> PatientSingleConclusionInfo(Table<O> child, ForeignKey<O, PatientSingleConclusionInfoRecord> key) {
        super(child, key, PATIENT_SINGLE_CONCLUSION_INFO);
    }

    @Override
    public Schema getSchema() {
        return PhysicalExaminationSystem.PHYSICAL_EXAMINATION_SYSTEM;
    }

    @Override
    public UniqueKey<PatientSingleConclusionInfoRecord> getPrimaryKey() {
        return Keys.KEY_PATIENT_SINGLE_CONCLUSION_INFO_PRIMARY;
    }

    @Override
    public List<UniqueKey<PatientSingleConclusionInfoRecord>> getKeys() {
        return Arrays.<UniqueKey<PatientSingleConclusionInfoRecord>>asList(Keys.KEY_PATIENT_SINGLE_CONCLUSION_INFO_PRIMARY);
    }

    @Override
    public PatientSingleConclusionInfo as(String alias) {
        return new PatientSingleConclusionInfo(DSL.name(alias), this);
    }

    @Override
    public PatientSingleConclusionInfo as(Name alias) {
        return new PatientSingleConclusionInfo(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PatientSingleConclusionInfo rename(String name) {
        return new PatientSingleConclusionInfo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PatientSingleConclusionInfo rename(Name name) {
        return new PatientSingleConclusionInfo(name, null);
    }

    // -------------------------------------------------------------------------
    // Row14 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row14<Long, String, String, LocalDateTime, Long, String, Integer, Integer, String, LocalDateTime, String, Long, String, Long> fieldsRow() {
        return (Row14) super.fieldsRow();
    }
}
