/*
 * This file is generated by jOOQ.
 */
package com.example.boot.data.database.jooq.tables;


import com.example.boot.data.database.jooq.Keys;
import com.example.boot.data.database.jooq.PhysicalExaminationSystem;
import com.example.boot.data.database.jooq.tables.records.PatientOrderItemInfoRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row19;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PatientOrderItemInfo extends TableImpl<PatientOrderItemInfoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>physical_examination_system.patient_order_item_info</code>
     */
    public static final PatientOrderItemInfo PATIENT_ORDER_ITEM_INFO = new PatientOrderItemInfo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PatientOrderItemInfoRecord> getRecordType() {
        return PatientOrderItemInfoRecord.class;
    }

    /**
     * The column <code>physical_examination_system.patient_order_item_info.id</code>.
     */
    public final TableField<PatientOrderItemInfoRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>physical_examination_system.patient_order_item_info.code</code>.
     */
    public final TableField<PatientOrderItemInfoRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>physical_examination_system.patient_order_item_info.created_by</code>.
     */
    public final TableField<PatientOrderItemInfoRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>physical_examination_system.patient_order_item_info.created_date</code>.
     */
    public final TableField<PatientOrderItemInfoRecord, LocalDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>physical_examination_system.patient_order_item_info.fee_item_code</code>.
     */
    public final TableField<PatientOrderItemInfoRecord, String> FEE_ITEM_CODE = createField(DSL.name("fee_item_code"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>physical_examination_system.patient_order_item_info.fee_item_id</code>.
     */
    public final TableField<PatientOrderItemInfoRecord, Long> FEE_ITEM_ID = createField(DSL.name("fee_item_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>physical_examination_system.patient_order_item_info.fee_item_name</code>.
     */
    public final TableField<PatientOrderItemInfoRecord, String> FEE_ITEM_NAME = createField(DSL.name("fee_item_name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>physical_examination_system.patient_order_item_info.is_deleted</code>.
     */
    public final TableField<PatientOrderItemInfoRecord, Integer> IS_DELETED = createField(DSL.name("is_deleted"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>physical_examination_system.patient_order_item_info.meal_code</code>.
     */
    public final TableField<PatientOrderItemInfoRecord, String> MEAL_CODE = createField(DSL.name("meal_code"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>physical_examination_system.patient_order_item_info.meal_id</code>.
     */
    public final TableField<PatientOrderItemInfoRecord, Long> MEAL_ID = createField(DSL.name("meal_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>physical_examination_system.patient_order_item_info.meal_name</code>.
     */
    public final TableField<PatientOrderItemInfoRecord, String> MEAL_NAME = createField(DSL.name("meal_name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>physical_examination_system.patient_order_item_info.modified_by</code>.
     */
    public final TableField<PatientOrderItemInfoRecord, String> MODIFIED_BY = createField(DSL.name("modified_by"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>physical_examination_system.patient_order_item_info.modified_date</code>.
     */
    public final TableField<PatientOrderItemInfoRecord, LocalDateTime> MODIFIED_DATE = createField(DSL.name("modified_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>physical_examination_system.patient_order_item_info.number</code>.
     */
    public final TableField<PatientOrderItemInfoRecord, Integer> NUMBER = createField(DSL.name("number"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>physical_examination_system.patient_order_item_info.patient_code</code>.
     */
    public final TableField<PatientOrderItemInfoRecord, String> PATIENT_CODE = createField(DSL.name("patient_code"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>physical_examination_system.patient_order_item_info.patient_id</code>.
     */
    public final TableField<PatientOrderItemInfoRecord, Long> PATIENT_ID = createField(DSL.name("patient_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>physical_examination_system.patient_order_item_info.total_price</code>.
     */
    public final TableField<PatientOrderItemInfoRecord, BigDecimal> TOTAL_PRICE = createField(DSL.name("total_price"), SQLDataType.DECIMAL(19, 2), this, "");

    /**
     * The column <code>physical_examination_system.patient_order_item_info.type</code>.
     */
    public final TableField<PatientOrderItemInfoRecord, Integer> TYPE = createField(DSL.name("type"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>physical_examination_system.patient_order_item_info.unit_price</code>.
     */
    public final TableField<PatientOrderItemInfoRecord, BigDecimal> UNIT_PRICE = createField(DSL.name("unit_price"), SQLDataType.DECIMAL(19, 2), this, "");

    private PatientOrderItemInfo(Name alias, Table<PatientOrderItemInfoRecord> aliased) {
        this(alias, aliased, null);
    }

    private PatientOrderItemInfo(Name alias, Table<PatientOrderItemInfoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>physical_examination_system.patient_order_item_info</code> table reference
     */
    public PatientOrderItemInfo(String alias) {
        this(DSL.name(alias), PATIENT_ORDER_ITEM_INFO);
    }

    /**
     * Create an aliased <code>physical_examination_system.patient_order_item_info</code> table reference
     */
    public PatientOrderItemInfo(Name alias) {
        this(alias, PATIENT_ORDER_ITEM_INFO);
    }

    /**
     * Create a <code>physical_examination_system.patient_order_item_info</code> table reference
     */
    public PatientOrderItemInfo() {
        this(DSL.name("patient_order_item_info"), null);
    }

    public <O extends Record> PatientOrderItemInfo(Table<O> child, ForeignKey<O, PatientOrderItemInfoRecord> key) {
        super(child, key, PATIENT_ORDER_ITEM_INFO);
    }

    @Override
    public Schema getSchema() {
        return PhysicalExaminationSystem.PHYSICAL_EXAMINATION_SYSTEM;
    }

    @Override
    public UniqueKey<PatientOrderItemInfoRecord> getPrimaryKey() {
        return Keys.KEY_PATIENT_ORDER_ITEM_INFO_PRIMARY;
    }

    @Override
    public List<UniqueKey<PatientOrderItemInfoRecord>> getKeys() {
        return Arrays.<UniqueKey<PatientOrderItemInfoRecord>>asList(Keys.KEY_PATIENT_ORDER_ITEM_INFO_PRIMARY);
    }

    @Override
    public PatientOrderItemInfo as(String alias) {
        return new PatientOrderItemInfo(DSL.name(alias), this);
    }

    @Override
    public PatientOrderItemInfo as(Name alias) {
        return new PatientOrderItemInfo(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PatientOrderItemInfo rename(String name) {
        return new PatientOrderItemInfo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PatientOrderItemInfo rename(Name name) {
        return new PatientOrderItemInfo(name, null);
    }

    // -------------------------------------------------------------------------
    // Row19 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row19<Long, String, String, LocalDateTime, String, Long, String, Integer, String, Long, String, String, LocalDateTime, Integer, String, Long, BigDecimal, Integer, BigDecimal> fieldsRow() {
        return (Row19) super.fieldsRow();
    }
}
