/*
 * This file is generated by jOOQ.
 */
package com.example.boot.data.database.jooq.tables;


import com.example.boot.data.database.jooq.Keys;
import com.example.boot.data.database.jooq.PhysicalExaminationSystem;
import com.example.boot.data.database.jooq.tables.records.SystemDepartmentInfoRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row13;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SystemDepartmentInfo extends TableImpl<SystemDepartmentInfoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>physical_examination_system.system_department_info</code>
     */
    public static final SystemDepartmentInfo SYSTEM_DEPARTMENT_INFO = new SystemDepartmentInfo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SystemDepartmentInfoRecord> getRecordType() {
        return SystemDepartmentInfoRecord.class;
    }

    /**
     * The column <code>physical_examination_system.system_department_info.id</code>.
     */
    public final TableField<SystemDepartmentInfoRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>physical_examination_system.system_department_info.code</code>.
     */
    public final TableField<SystemDepartmentInfoRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>physical_examination_system.system_department_info.created_by</code>.
     */
    public final TableField<SystemDepartmentInfoRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>physical_examination_system.system_department_info.created_date</code>.
     */
    public final TableField<SystemDepartmentInfoRecord, LocalDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>physical_examination_system.system_department_info.is_deleted</code>.
     */
    public final TableField<SystemDepartmentInfoRecord, Integer> IS_DELETED = createField(DSL.name("is_deleted"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>physical_examination_system.system_department_info.is_enabled</code>.
     */
    public final TableField<SystemDepartmentInfoRecord, Integer> IS_ENABLED = createField(DSL.name("is_enabled"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>physical_examination_system.system_department_info.modified_by</code>.
     */
    public final TableField<SystemDepartmentInfoRecord, String> MODIFIED_BY = createField(DSL.name("modified_by"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>physical_examination_system.system_department_info.modified_date</code>.
     */
    public final TableField<SystemDepartmentInfoRecord, LocalDateTime> MODIFIED_DATE = createField(DSL.name("modified_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>physical_examination_system.system_department_info.name</code>.
     */
    public final TableField<SystemDepartmentInfoRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>physical_examination_system.system_department_info.p_code</code>.
     */
    public final TableField<SystemDepartmentInfoRecord, String> P_CODE = createField(DSL.name("p_code"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>physical_examination_system.system_department_info.parent_id</code>.
     */
    public final TableField<SystemDepartmentInfoRecord, Long> PARENT_ID = createField(DSL.name("parent_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>physical_examination_system.system_department_info.type</code>.
     */
    public final TableField<SystemDepartmentInfoRecord, Integer> TYPE = createField(DSL.name("type"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>physical_examination_system.system_department_info.weight</code>.
     */
    public final TableField<SystemDepartmentInfoRecord, Integer> WEIGHT = createField(DSL.name("weight"), SQLDataType.INTEGER, this, "");

    private SystemDepartmentInfo(Name alias, Table<SystemDepartmentInfoRecord> aliased) {
        this(alias, aliased, null);
    }

    private SystemDepartmentInfo(Name alias, Table<SystemDepartmentInfoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>physical_examination_system.system_department_info</code> table reference
     */
    public SystemDepartmentInfo(String alias) {
        this(DSL.name(alias), SYSTEM_DEPARTMENT_INFO);
    }

    /**
     * Create an aliased <code>physical_examination_system.system_department_info</code> table reference
     */
    public SystemDepartmentInfo(Name alias) {
        this(alias, SYSTEM_DEPARTMENT_INFO);
    }

    /**
     * Create a <code>physical_examination_system.system_department_info</code> table reference
     */
    public SystemDepartmentInfo() {
        this(DSL.name("system_department_info"), null);
    }

    public <O extends Record> SystemDepartmentInfo(Table<O> child, ForeignKey<O, SystemDepartmentInfoRecord> key) {
        super(child, key, SYSTEM_DEPARTMENT_INFO);
    }

    @Override
    public Schema getSchema() {
        return PhysicalExaminationSystem.PHYSICAL_EXAMINATION_SYSTEM;
    }

    @Override
    public UniqueKey<SystemDepartmentInfoRecord> getPrimaryKey() {
        return Keys.KEY_SYSTEM_DEPARTMENT_INFO_PRIMARY;
    }

    @Override
    public List<UniqueKey<SystemDepartmentInfoRecord>> getKeys() {
        return Arrays.<UniqueKey<SystemDepartmentInfoRecord>>asList(Keys.KEY_SYSTEM_DEPARTMENT_INFO_PRIMARY);
    }

    @Override
    public SystemDepartmentInfo as(String alias) {
        return new SystemDepartmentInfo(DSL.name(alias), this);
    }

    @Override
    public SystemDepartmentInfo as(Name alias) {
        return new SystemDepartmentInfo(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SystemDepartmentInfo rename(String name) {
        return new SystemDepartmentInfo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SystemDepartmentInfo rename(Name name) {
        return new SystemDepartmentInfo(name, null);
    }

    // -------------------------------------------------------------------------
    // Row13 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row13<Long, String, String, LocalDateTime, Integer, Integer, String, LocalDateTime, String, String, Long, Integer, Integer> fieldsRow() {
        return (Row13) super.fieldsRow();
    }
}
